//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoWard.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7812,3560,200,3,12,617
        ///7976.8247,4281.9023,200,3,15,290
        ///7074,3112,200,3,12,206
        ///3276,7786,200,3,12,167
        ///7468,4990,200,3,11,153
        ///11856,3834,200,3,25,117
        ///5208,9158,200,3,25,111
        ///9406,5620,200,3,37,109
        ///12464,1446,200,3,32,105
        ///13528,2644,200,3,41,100
        ///10602,2988,200,3,95,95
        ///8636,6646,200,3,16,90
        ///13108,2014,200,3,44,85
        ///2996,10984,200,3,17,84
        ///8500,4806,200,3,17,80
        ///2876,11262,200,3,36,74
        ///.
        /// </summary>
        public static string wards_Chaos_All_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7812,3560,200,3,12,617
        ///7976.8247,4281.9023,200,3,15,290
        ///7074,3112,200,3,12,206
        ///3276,7786,200,3,12,167
        ///7468,4990,200,3,11,153
        ///11856,3834,200,3,25,117
        ///5208,9158,200,3,25,111
        ///9406,5620,200,3,37,109
        ///12464,1446,200,3,32,105
        ///13528,2644,200,3,41,100
        ///10602,2988,200,3,95,95
        ///8636,6646,200,3,16,90
        ///13108,2014,200,3,44,85
        ///2996,10984,200,3,17,84
        ///8500,4806,200,3,17,80
        ///2876,11262,200,3,36,74
        ///.
        /// </summary>
        public static string wards_Chaos_All_01 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3110,8976,200,3,23,200
        ///6584,4666,200,3,71,187
        ///7078,3104,200,3,20,178
        ///10372,4430,200,3,14,172
        ///3262,7810,200,3,21,152
        ///4750,7198,200,3,14,152
        ///8320,10226,200,3,11,149
        ///7840,3618,200,3,11,147
        ///8280,6346,200,3,25,134
        ///6821.5615,5610.3203,200,3,13,131
        ///9386,5678,200,3,222,129
        ///9170,2112,200,3,26,126
        ///8980.241,4914.1094,200,3,11,123
        ///11762,3966,200,3,232,122
        ///5212,9142,200,3,89,121
        ///9684,6332,200,3,49,121
        ///11602,7062,200,3,18,116
        ///4498,11886,200,3,33,110
        ///8554,6514,200,3,56,110
        ///10052,4664,200,3,5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3110,8976,200,3,23,200
        ///6584,4666,200,3,71,187
        ///7078,3104,200,3,20,178
        ///10372,4430,200,3,14,172
        ///3262,7810,200,3,21,152
        ///4750,7198,200,3,14,152
        ///8320,10226,200,3,11,149
        ///7840,3618,200,3,11,147
        ///8280,6346,200,3,25,134
        ///6821.5615,5610.3203,200,3,13,131
        ///9386,5678,200,3,222,129
        ///9170,2112,200,3,26,126
        ///8980.241,4914.1094,200,3,11,123
        ///11762,3966,200,3,232,122
        ///5212,9142,200,3,89,121
        ///9684,6332,200,3,49,121
        ///11602,7062,200,3,18,116
        ///4498,11886,200,3,33,110
        ///8554,6514,200,3,56,110
        ///10052,4664,200,3,5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_101 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11904,5804,200,3,32,193
        ///7873.926,6007.075,200,3,29,162
        ///6766,3106,200,3,29,161
        ///3086,9016,200,3,23,161
        ///8154,5804,200,3,20,161
        ///6827.8184,5607.4766,200,3,23,157
        ///10172,4618,200,3,33,154
        ///9828,4762,200,3,13,154
        ///5254,9142,200,3,111,144
        ///6610,4758,200,3,111,140
        ///9394,5688,200,3,242,140
        ///4876,8318,200,3,30,138
        ///11544,7094,200,3,68,137
        ///3270,7834,200,3,32,137
        ///8288,4850,200,3,18,132
        ///5482,10520,200,3,15,132
        ///8566,4726,200,3,102,132
        ///9802,6340,200,3,41,130
        ///5545.8403,3412.0703,200,3,20,126
        ///10454,30 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4768,10290,200,3,13,226
        ///5166,8556,200,3,23,210
        ///8040,5810,200,3,18,198
        ///7064,3124,200,3,26,163
        ///5168,9170,200,3,71,159
        ///4492,11652,200,3,12,158
        ///5634.593,7873.049,200,3,16,152
        ///5478.2866,10455.166,200,3,47,147
        ///9123.142,11427.736,200,3,14,146
        ///6552,4732,200,3,137,142
        ///8116,6254,200,3,11,142
        ///8540,4790,200,3,99,141
        ///3281.7305,7689.924,200,3,23,139
        ///6752,3108,200,3,35,139
        ///3066,9062,200,3,40,135
        ///9444,5586,200,3,106,133
        ///7120.034,5611.996,200,3,11,133
        ///11628,7082,200,3,27,132
        ///8432,6448,200,3,34 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4768,10290,200,3,13,226
        ///5166,8556,200,3,23,210
        ///8040,5810,200,3,18,198
        ///7064,3124,200,3,26,163
        ///5168,9170,200,3,71,159
        ///4492,11652,200,3,12,158
        ///5634.593,7873.049,200,3,16,152
        ///5478.2866,10455.166,200,3,47,147
        ///9123.142,11427.736,200,3,14,146
        ///6552,4732,200,3,137,142
        ///8116,6254,200,3,11,142
        ///8540,4790,200,3,99,141
        ///3281.7305,7689.924,200,3,23,139
        ///6752,3108,200,3,35,139
        ///3066,9062,200,3,40,135
        ///9444,5586,200,3,106,133
        ///7120.034,5611.996,200,3,11,133
        ///11628,7082,200,3,27,132
        ///8432,6448,200,3,34 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_201 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3086,8976,200,3,16,182
        ///6586,4760,200,3,68,167
        ///9434,5650,200,3,76,162
        ///6562,8400,200,3,15,159
        ///11614,7146,200,3,24,145
        ///6820.3203,5606.577,200,3,12,137
        ///3402,7808,200,3,26,134
        ///5514,3488,200,3,22,131
        ///4810,7206,200,3,30,131
        ///5250,9136,200,3,53,131
        ///10166,4732,200,3,13,129
        ///6873.938,8629.194,200,3,44,128
        ///4898,8352,200,3,34,128
        ///6746,3180,200,3,21,126
        ///8780.332,6723.504,200,3,22,124
        ///4840,10222,200,3,16,111
        ///11884,5838,200,3,16,111
        ///8342,10210,200,3,52,109
        ///9775.846,6457.1895,200,3,32,107
        ///8560, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_25 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8520,4816,200,3,21,209
        ///4968.4683,8345.7,200,3,13,185
        ///4842,7190,200,3,14,167
        ///9464,5616,200,3,28,150
        ///3068,8984,200,3,12,137
        ///6546,4724,200,3,32,136
        ///5489.8643,10558.087,200,3,13,126
        ///5152,9100,200,3,11,102
        ///10422,3058,200,3,11,96
        ///.
        /// </summary>
        public static string wards_Chaos_All_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8520,4816,200,3,21,209
        ///4968.4683,8345.7,200,3,13,185
        ///4842,7190,200,3,14,167
        ///9464,5616,200,3,28,150
        ///3068,8984,200,3,12,137
        ///6546,4724,200,3,32,136
        ///5489.8643,10558.087,200,3,13,126
        ///5152,9100,200,3,11,102
        ///10422,3058,200,3,11,96
        ///.
        /// </summary>
        public static string wards_Chaos_All_301 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_All_35 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_All_40 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3338,7734,200,3,17,195
        ///8726,6586,200,3,17,154
        ///10377.9375,4516.994,200,3,12,147
        ///5220,9108,200,3,63,136
        ///9450,5640,200,3,171,133
        ///10044,4714,200,3,28,129
        ///9714,6362,200,3,39,123
        ///10348,3156,200,3,17,115
        ///8522,4916,200,3,74,111
        ///11792,3906,200,3,169,110
        ///12164,1312,200,3,44,107
        ///6547.0156,4851.652,200,3,11,104
        ///8260,5726,200,3,12,96
        ///8142,6322,200,3,12,94
        ///13128,2068,200,3,59,90
        ///4168,11884,200,3,15,90
        ///3106,10846,200,3,138,88
        ///13472,2758,200,3,92,85
        ///4478,11770,200,3,26,84
        ///6384,8274,200,3,12,8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_5 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_101 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6568,4722,200,2,20,91
        ///9988,4742,200,2,11,84
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8500,4764,200,2,18,196
        ///4834,7130,200,2,11,159
        ///11854,5872,200,2,11,142
        ///5260,9162,200,2,12,107
        ///8250,10270,200,2,15,82
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8500,4764,200,2,18,196
        ///4834,7130,200,2,11,159
        ///11854,5872,200,2,11,142
        ///5260,9162,200,2,12,107
        ///8250,10270,200,2,15,82
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_201 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3366,7770,200,2,18,135
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_25 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_35 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_40 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Control_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Control_01 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3086,9040,200,0,15,283
        ///3370,7754,200,0,12,222
        ///6536,4708,200,0,16,183
        ///9440,5636,200,0,139,148
        ///11784,5946,200,0,19,142
        ///5314,9180,200,0,38,141
        ///11496,7124,200,0,13,139
        ///8540,4762,200,0,38,134
        ///11756,3872,200,0,58,133
        ///11928,3624,200,0,19,127
        ///11944.586,4109.681,200,0,28,120
        ///4544,11888,200,0,19,116
        ///8690.723,6775.2773,200,0,17,110
        ///10122,4636,200,0,47,108
        ///6760,8572,200,0,31,108
        ///12572,5280,200,0,13,104
        ///10544,3028,200,0,45,104
        ///2986,10952,200,0,23,104
        ///13456,2632,200,0,12,80
        ///12616,4948,200,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3086,9040,200,0,15,283
        ///3370,7754,200,0,12,222
        ///6536,4708,200,0,16,183
        ///9440,5636,200,0,139,148
        ///11784,5946,200,0,19,142
        ///5314,9180,200,0,38,141
        ///11496,7124,200,0,13,139
        ///8540,4762,200,0,38,134
        ///11756,3872,200,0,58,133
        ///11928,3624,200,0,19,127
        ///11944.586,4109.681,200,0,28,120
        ///4544,11888,200,0,19,116
        ///8690.723,6775.2773,200,0,17,110
        ///10122,4636,200,0,47,108
        ///6760,8572,200,0,31,108
        ///12572,5280,200,0,13,104
        ///10544,3028,200,0,45,104
        ///2986,10952,200,0,23,104
        ///13456,2632,200,0,12,80
        ///12616,4948,200,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_101 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11910,5922,200,0,18,191
        ///5220,9148,200,0,55,162
        ///6314,10122,200,0,21,158
        ///9444,5662,200,0,112,149
        ///11538,7120,200,0,33,149
        ///9730,6390,200,0,36,148
        ///3306,7806,200,0,21,148
        ///6598,4632,200,0,35,143
        ///7066,3070,200,0,14,141
        ///10110,4716,200,0,43,138
        ///8502,4882,200,0,37,127
        ///6580,8388,200,0,14,121
        ///3082,10868,200,0,18,120
        ///6852,8598,200,0,22,113
        ///4854,7116,200,0,15,110
        ///11844,4040,200,0,34,108
        ///8252,10318,200,0,19,107
        ///10000,7830,200,0,20,97
        ///8596,6642,200,0,35,94
        ///10330,3072,200,0,22,94
        ///12622,5002,200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5242,9152,200,0,45,209
        ///6490,4638,200,0,21,172
        ///9771.134,6458.643,200,0,11,149
        ///3278,7810,200,0,11,146
        ///9416,5668,200,0,46,123
        ///6212,10214,200,0,16,114
        ///8244,10234,200,0,41,111
        ///4714,7198,200,0,11,108
        ///10080,4690,200,0,12,86
        ///.
        /// </summary>
        public static string wards_Chaos_Control_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5242,9152,200,0,45,209
        ///6490,4638,200,0,21,172
        ///9771.134,6458.643,200,0,11,149
        ///3278,7810,200,0,11,146
        ///9416,5668,200,0,46,123
        ///6212,10214,200,0,16,114
        ///8244,10234,200,0,41,111
        ///4714,7198,200,0,11,108
        ///10080,4690,200,0,12,86
        ///.
        /// </summary>
        public static string wards_Chaos_Control_201 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6604,4724,200,0,16,176
        ///5234,9196,200,0,15,158
        ///9402,5662,200,0,17,131
        ///8246,10200,200,0,21,123
        ///4772,10126,200,0,11,89
        ///.
        /// </summary>
        public static string wards_Chaos_Control_25 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Control_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Control_35 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Control_40 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5218,9188,200,0,40,159
        ///4478,11770,200,0,11,144
        ///9358,5586,200,0,53,138
        ///8590,4794,200,0,34,138
        ///11864,3716,200,0,34,137
        ///10176,4734,200,0,19,132
        ///9778,6432,200,0,13,129
        ///11818,4022,200,0,159,123
        ///2916,11262,200,0,14,123
        ///3094,10796,200,0,37,122
        ///10635.563,3014.5674,200,0,20,107
        ///8773.559,6706.8457,200,0,15,96
        ///13536,2728,200,0,12,91
        ///6712,8434,200,0,13,87
        ///12612,4864,200,0,11,69
        ///.
        /// </summary>
        public static string wards_Chaos_Control_5 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7820,3578,200,1,12,617
        ///8028.125,4262.7646,200,1,15,290
        ///7134,3144,200,1,12,206
        ///6592,4692,200,1,22,145
        ///12524,1420,200,1,18,124
        ///5324,9172,200,1,29,107
        ///11796,3912,200,1,27,100
        ///13608,2776,200,1,40,98
        ///12208,1316,200,1,11,92
        ///6552,8360,200,1,16,87
        ///10624,3018,200,1,92,87
        ///9474,5612,200,1,22,85
        ///13046,2050,200,1,47,79
        ///3012,10980,200,1,21,77
        ///4890,8372,200,1,11,44
        ///6884.1177,8612.114,200,1,19,43
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7820,3578,200,1,12,617
        ///8028.125,4262.7646,200,1,15,290
        ///7134,3144,200,1,12,206
        ///6592,4692,200,1,22,145
        ///12524,1420,200,1,18,124
        ///5324,9172,200,1,29,107
        ///11796,3912,200,1,27,100
        ///13608,2776,200,1,40,98
        ///12208,1316,200,1,11,92
        ///6552,8360,200,1,16,87
        ///10624,3018,200,1,92,87
        ///9474,5612,200,1,22,85
        ///13046,2050,200,1,47,79
        ///3012,10980,200,1,21,77
        ///4890,8372,200,1,11,44
        ///6884.1177,8612.114,200,1,19,43
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_01 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6548,4788,200,1,41,166
        ///7840,3552,200,1,14,131
        ///6826.664,5632.213,200,1,15,125
        ///10244,2948,200,1,36,124
        ///11760,3966,200,1,77,123
        ///9350,5650,200,1,66,115
        ///9472.588,2157.926,200,1,27,111
        ///8168,5832,200,1,18,110
        ///10576,3038,200,1,272,109
        ///8424,6492,200,1,28,109
        ///12608,5090,200,1,14,105
        ///8506,4744,200,1,59,102
        ///13372,2492,200,1,15,99
        ///13560,2760,200,1,78,91
        ///9700,6412,200,1,29,91
        ///11934.144,5914.749,200,1,17,90
        ///4174,11884,200,1,19,89
        ///4568,11914,200,1,18,89
        ///5134,8522,200,1,20,87
        ///2574,13494,200,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6548,4788,200,1,41,166
        ///7840,3552,200,1,14,131
        ///6826.664,5632.213,200,1,15,125
        ///10244,2948,200,1,36,124
        ///11760,3966,200,1,77,123
        ///9350,5650,200,1,66,115
        ///9472.588,2157.926,200,1,27,111
        ///8168,5832,200,1,18,110
        ///10576,3038,200,1,272,109
        ///8424,6492,200,1,28,109
        ///12608,5090,200,1,14,105
        ///8506,4744,200,1,59,102
        ///13372,2492,200,1,15,99
        ///13560,2760,200,1,78,91
        ///9700,6412,200,1,29,91
        ///11934.144,5914.749,200,1,17,90
        ///4174,11884,200,1,19,89
        ///4568,11914,200,1,18,89
        ///5134,8522,200,1,20,87
        ///2574,13494,200,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_101 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6510,4582,200,1,37,186
        ///5623.84,3510.7607,200,1,13,179
        ///5423.831,7909.2617,200,1,15,172
        ///6822.232,5619.7793,200,1,20,152
        ///6766,3092,200,1,18,152
        ///7820,5852,200,1,11,144
        ///8388,6456,200,1,27,139
        ///9472,5640,200,1,144,137
        ///11596,7106,200,1,32,137
        ///8510,4736,200,1,77,128
        ///7063.0166,3168.3008,200,1,18,128
        ///5196,9150,200,1,38,124
        ///9312,3770,200,1,15,123
        ///12671.977,5457.748,200,1,25,118
        ///3110,9008,200,1,12,117
        ///9799.93,6529.0986,200,1,49,115
        ///3020.3225,10803.866,200,1,15,114
        ///8782.461,6724.3594,200,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7067.7207,3171.7617,200,1,12,189
        ///11810,4042,200,1,12,182
        ///8434,6476,200,1,19,165
        ///3372,7738,200,1,23,154
        ///5574.626,7866.6167,200,1,15,152
        ///9436,5616,200,1,91,150
        ///5248,9156,200,1,74,150
        ///6600,4722,200,1,73,137
        ///5020,8396,200,1,35,136
        ///5476,3482,200,1,17,131
        ///8488,4810,200,1,72,130
        ///5480.1563,10510.371,200,1,31,129
        ///11546,7168,200,1,25,128
        ///8689.5625,6769.5977,200,1,35,127
        ///9764,6392,200,1,52,125
        ///3066,9124,200,1,15,119
        ///5242.7285,10924.869,200,1,13,115
        ///6502,8366,200,1,16,113
        ///5174.785,7964.71 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7067.7207,3171.7617,200,1,12,189
        ///11810,4042,200,1,12,182
        ///8434,6476,200,1,19,165
        ///3372,7738,200,1,23,154
        ///5574.626,7866.6167,200,1,15,152
        ///9436,5616,200,1,91,150
        ///5248,9156,200,1,74,150
        ///6600,4722,200,1,73,137
        ///5020,8396,200,1,35,136
        ///5476,3482,200,1,17,131
        ///8488,4810,200,1,72,130
        ///5480.1563,10510.371,200,1,31,129
        ///11546,7168,200,1,25,128
        ///8689.5625,6769.5977,200,1,35,127
        ///9764,6392,200,1,52,125
        ///3066,9124,200,1,15,119
        ///5242.7285,10924.869,200,1,13,115
        ///6502,8366,200,1,16,113
        ///5174.785,7964.71 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_201 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9362,5654,200,1,43,190
        ///8660,4720,200,1,11,180
        ///6536,4752,200,1,50,174
        ///6716,3164,200,1,11,144
        ///4974,8436,200,1,23,138
        ///9704,6422,200,1,28,132
        ///6825.066,5605.2773,200,1,15,125
        ///11440,7174,200,1,16,124
        ///4794,7070,200,1,19,123
        ///5224.6836,7960.04,200,1,17,122
        ///8773.102,6703.582,200,1,19,116
        ///6800,8594,200,1,41,114
        ///5478.256,10456.549,200,1,17,113
        ///8300,10298,200,1,33,109
        ///5318,9168,200,1,25,109
        ///6342,10136,200,1,22,77
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_25 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8524,4830,200,1,16,235
        ///8208,10156,200,1,11,228
        ///4986.9087,8338.841,200,1,11,164
        ///9446,5638,200,1,16,158
        ///6486,4698,200,1,17,116
        ///6854,8598,200,1,23,71
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8524,4830,200,1,16,235
        ///8208,10156,200,1,11,228
        ///4986.9087,8338.841,200,1,11,164
        ///9446,5638,200,1,16,158
        ///6486,4698,200,1,17,116
        ///6854,8598,200,1,23,71
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_301 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_35 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_40 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7446,4946,200,1,11,124
        ///5184,9184,200,1,19,113
        ///6610,4768,200,1,16,106
        ///8572,4736,200,1,26,101
        ///10322,2992,200,1,30,98
        ///11750,4122,200,1,24,98
        ///11872,3814,200,1,47,95
        ///10636.292,3015.6433,200,1,254,94
        ///9286,2150,200,1,15,90
        ///8000,5790,200,1,11,89
        ///9458,5638,200,1,52,88
        ///12204,1276,200,1,46,87
        ///6988,5628,200,1,16,86
        ///13032,2010,200,1,89,80
        ///13530,2652,200,1,84,77
        ///8794.059,6731.3203,200,1,59,77
        ///2902,11252,200,1,82,70
        ///12600,4976,200,1,12,67
        ///12450,1472,200,1,62,66
        ///3018,10970,200,1,47,65
        ///8512,66 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_5 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6996,11334,100,3,18,231
        ///7792,11808,100,3,12,153
        ///9380,5648,100,3,48,147
        ///8230,10234,100,3,33,129
        ///12314,1418,100,3,36,102
        ///11760,4034,100,3,57,99
        ///2922,11320,100,3,25,94
        ///13382,2520,100,3,36,88
        ///5224,9078,100,3,24,88
        ///3010,10988,100,3,13,88
        ///8116,6206,100,3,31,86
        ///11900,3762,100,3,39,80
        ///13044,2020,100,3,11,75
        ///4182,11798,100,3,20,71
        ///10278,2892,100,3,22,44
        ///.
        /// </summary>
        public static string wards_Order_All_0 {
            get {
                return ResourceManager.GetString("wards_Order_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6996,11334,100,3,18,231
        ///7792,11808,100,3,12,153
        ///9380,5648,100,3,48,147
        ///8230,10234,100,3,33,129
        ///12314,1418,100,3,36,102
        ///11760,4034,100,3,57,99
        ///2922,11320,100,3,25,94
        ///13382,2520,100,3,36,88
        ///5224,9078,100,3,24,88
        ///3010,10988,100,3,13,88
        ///8116,6206,100,3,31,86
        ///11900,3762,100,3,39,80
        ///13044,2020,100,3,11,75
        ///4182,11798,100,3,20,71
        ///10278,2892,100,3,22,44
        ///.
        /// </summary>
        public static string wards_Order_All_01 {
            get {
                return ResourceManager.GetString("wards_Order_All_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11608,7058,100,3,43,181
        ///11919.464,6498.894,100,3,14,175
        ///3028,9066,100,3,14,156
        ///11986,5796,100,3,12,141
        ///5126,8536,100,3,22,137
        ///5258,9130,100,3,101,135
        ///10018,7784,100,3,40,134
        ///11900,3654,100,3,71,128
        ///2220,9874,100,3,11,125
        ///12049.523,4561.484,100,3,21,125
        ///9452,5674,100,3,192,120
        ///12590,4870,100,3,58,120
        ///12982,1940,100,3,50,118
        ///11790,4008,100,3,321,117
        ///6276,10138,100,3,45,117
        ///9708,6430,100,3,44,112
        ///8518,4874,100,3,63,112
        ///9172.067,7046.001,100,3,25,112
        ///8569.2705,4557.7686,100,3,13,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_10 {
            get {
                return ResourceManager.GetString("wards_Order_All_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11608,7058,100,3,43,181
        ///11919.464,6498.894,100,3,14,175
        ///3028,9066,100,3,14,156
        ///11986,5796,100,3,12,141
        ///5126,8536,100,3,22,137
        ///5258,9130,100,3,101,135
        ///10018,7784,100,3,40,134
        ///11900,3654,100,3,71,128
        ///2220,9874,100,3,11,125
        ///12049.523,4561.484,100,3,21,125
        ///9452,5674,100,3,192,120
        ///12590,4870,100,3,58,120
        ///12982,1940,100,3,50,118
        ///11790,4008,100,3,321,117
        ///6276,10138,100,3,45,117
        ///9708,6430,100,3,44,112
        ///8518,4874,100,3,63,112
        ///9172.067,7046.001,100,3,25,112
        ///8569.2705,4557.7686,100,3,13,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_101 {
            get {
                return ResourceManager.GetString("wards_Order_All_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11823.938,6536.563,100,3,11,201
        ///11624,7098,100,3,44,178
        ///8154,11758,100,3,21,177
        ///11930,7454,100,3,21,171
        ///11728,5916,100,3,66,165
        ///9315.941,4515.456,100,3,16,150
        ///8318,10214,100,3,124,139
        ///6708,3126,100,3,13,138
        ///3002,8928,100,3,18,137
        ///3328,7714,100,3,48,131
        ///7923.3486,9301.223,100,3,19,131
        ///9672.791,6892.376,100,3,38,130
        ///9708,3890,100,3,20,127
        ///5246,9174,100,3,123,127
        ///9110.539,7100.4297,100,3,48,124
        ///7072.301,3162.1426,100,3,24,122
        ///8152,6122,100,3,67,122
        ///9718,6350,100,3,62,120
        ///9960,787 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_15 {
            get {
                return ResourceManager.GetString("wards_Order_All_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5237.7876,10002.558,100,3,18,233
        ///9661.038,6892.614,100,3,15,189
        ///11122.844,6106.9434,100,3,11,171
        ///5040,8488,100,3,52,165
        ///7823.9697,9307.276,100,3,20,158
        ///8332,6458,100,3,25,158
        ///7854,11812,100,3,28,156
        ///9307.167,6983.1772,100,3,16,154
        ///5266,9120,100,3,276,152
        ///9384,11484,100,3,17,152
        ///6582,8364,100,3,25,151
        ///9430,5628,100,3,123,148
        ///4958,10174,100,3,46,139
        ///8358,10142,100,3,62,138
        ///10166,4730,100,3,11,136
        ///6330,10040,100,3,71,135
        ///9818,6488,100,3,45,135
        ///7068,3058,100,3,22,132
        ///9052,2078,100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_20 {
            get {
                return ResourceManager.GetString("wards_Order_All_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5237.7876,10002.558,100,3,18,233
        ///9661.038,6892.614,100,3,15,189
        ///11122.844,6106.9434,100,3,11,171
        ///5040,8488,100,3,52,165
        ///7823.9697,9307.276,100,3,20,158
        ///8332,6458,100,3,25,158
        ///7854,11812,100,3,28,156
        ///9307.167,6983.1772,100,3,16,154
        ///5266,9120,100,3,276,152
        ///9384,11484,100,3,17,152
        ///6582,8364,100,3,25,151
        ///9430,5628,100,3,123,148
        ///4958,10174,100,3,46,139
        ///8358,10142,100,3,62,138
        ///10166,4730,100,3,11,136
        ///6330,10040,100,3,71,135
        ///9818,6488,100,3,45,135
        ///7068,3058,100,3,22,132
        ///9052,2078,100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_201 {
            get {
                return ResourceManager.GetString("wards_Order_All_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8160,6240,100,3,59,153
        ///10004,7766,100,3,36,150
        ///5246,9126,100,3,67,145
        ///6270,10168,100,3,44,141
        ///4972.1953,8345.428,100,3,25,135
        ///4942,10134,100,3,26,132
        ///9324,5646,100,3,36,125
        ///3298,7798,100,3,23,124
        ///6500,4666,100,3,66,117
        ///9868,6498,100,3,36,112
        ///8494,4794,100,3,38,107
        ///8238,11768,100,3,11,106
        ///5692,3526,100,3,22,104
        ///8217.616,3556.6357,100,3,12,104
        ///6950,3100,100,3,27,95
        ///8342,10384,100,3,12,93
        ///.
        /// </summary>
        public static string wards_Order_All_25 {
            get {
                return ResourceManager.GetString("wards_Order_All_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9853.0205,6548.2734,100,3,13,125
        ///6552,4716,100,3,30,120
        ///5268,9130,100,3,28,115
        ///9430,5676,100,3,31,105
        ///5072,8452,100,3,13,104
        ///.
        /// </summary>
        public static string wards_Order_All_30 {
            get {
                return ResourceManager.GetString("wards_Order_All_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_All_35 {
            get {
                return ResourceManager.GetString("wards_Order_All_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_All_40 {
            get {
                return ResourceManager.GetString("wards_Order_All_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11790,5916,100,3,55,197
        ///11504,7104,100,3,11,144
        ///9430,5706,100,3,162,136
        ///5202,9124,100,3,61,136
        ///11940,3954,100,3,59,121
        ///8342,6374,100,3,53,117
        ///11622.088,5157.4014,100,3,15,114
        ///11910,3648,100,3,91,112
        ///8540,4882,100,3,27,112
        ///13500,2846,100,3,22,112
        ///10372,3062,100,3,106,107
        ///12264,1340,100,3,82,105
        ///9950,6618,100,3,14,101
        ///3108,10848,100,3,99,99
        ///13408,2524,100,3,94,98
        ///6290,10162,100,3,17,92
        ///7046,11366,100,3,14,90
        ///12874,1844,100,3,63,89
        ///4478,11746,100,3,26,89
        ///12633.043,4848.049,100,3, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_5 {
            get {
                return ResourceManager.GetString("wards_Order_All_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_10 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_101 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9416,5660,100,2,15,128
        ///8264,10262,100,2,15,125
        ///6264,10120,100,2,11,116
        ///.
        /// </summary>
        public static string wards_Order_Blue_15 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6408,8276,100,2,12,95
        ///8288,10290,100,2,14,88
        ///6284,10180,100,2,18,86
        ///4812,7152,100,2,11,72
        ///6526,4680,100,2,12,67
        ///.
        /// </summary>
        public static string wards_Order_Blue_20 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6408,8276,100,2,12,95
        ///8288,10290,100,2,14,88
        ///6284,10180,100,2,18,86
        ///4812,7152,100,2,11,72
        ///6526,4680,100,2,12,67
        ///.
        /// </summary>
        public static string wards_Order_Blue_201 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_25 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_30 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_35 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Blue_40 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Control_0 {
            get {
                return ResourceManager.GetString("wards_Order_Control_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Control_01 {
            get {
                return ResourceManager.GetString("wards_Order_Control_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11730,5888,100,0,28,205
        ///11566,7132,100,0,22,204
        ///5242,9140,100,0,68,161
        ///6328,10084,100,0,23,150
        ///10000,7852,100,0,13,142
        ///9452,5674,100,0,92,139
        ///11726,4024,100,0,72,138
        ///11872,3654,100,0,14,137
        ///8178,6262,100,0,68,129
        ///8502,4802,100,0,54,125
        ///2924,11162,100,0,30,112
        ///10076,4728,100,0,21,110
        ///10312,2918,100,0,206,109
        ///3118,10842,100,0,44,105
        ///6269.7188,8051.0894,100,0,11,84
        ///.
        /// </summary>
        public static string wards_Order_Control_10 {
            get {
                return ResourceManager.GetString("wards_Order_Control_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11730,5888,100,0,28,205
        ///11566,7132,100,0,22,204
        ///5242,9140,100,0,68,161
        ///6328,10084,100,0,23,150
        ///10000,7852,100,0,13,142
        ///9452,5674,100,0,92,139
        ///11726,4024,100,0,72,138
        ///11872,3654,100,0,14,137
        ///8178,6262,100,0,68,129
        ///8502,4802,100,0,54,125
        ///2924,11162,100,0,30,112
        ///10076,4728,100,0,21,110
        ///10312,2918,100,0,206,109
        ///3118,10842,100,0,44,105
        ///6269.7188,8051.0894,100,0,11,84
        ///.
        /// </summary>
        public static string wards_Order_Control_101 {
            get {
                return ResourceManager.GetString("wards_Order_Control_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3424.2852,7706.4688,100,0,13,207
        ///11576,7088,100,0,22,187
        ///9990,7816,100,0,26,179
        ///9758.315,6471.8345,100,0,11,150
        ///5178,9158,100,0,37,145
        ///11874,5910,100,0,20,142
        ///8246,10292,100,0,27,136
        ///9434,5652,100,0,80,132
        ///6454,8228,100,0,12,127
        ///6574,4690,100,0,37,118
        ///11798,4012,100,0,29,116
        ///3130,10784,100,0,17,113
        ///8628,4732,100,0,25,108
        ///10224,2936,100,0,77,106
        ///8104,6208,100,0,52,104
        ///10180,4694,100,0,15,90
        ///4504,11730,100,0,12,86
        ///6342,10104,100,0,21,74
        ///.
        /// </summary>
        public static string wards_Order_Control_15 {
            get {
                return ResourceManager.GetString("wards_Order_Control_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9504,5638,100,0,29,161
        ///5126.5938,8444.857,100,0,11,161
        ///5144,9164,100,0,26,153
        ///8304,10176,100,0,35,148
        ///3346,7692,100,0,14,138
        ///6608,4706,100,0,33,134
        ///8172,6298,100,0,19,128
        ///2964,9002,100,0,11,124
        ///10380,3022,100,0,11,119
        ///6302,10152,100,0,18,104
        ///10032,7800,100,0,19,103
        ///11554,7072,100,0,11,103
        ///8612,4658,100,0,14,79
        ///.
        /// </summary>
        public static string wards_Order_Control_20 {
            get {
                return ResourceManager.GetString("wards_Order_Control_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9504,5638,100,0,29,161
        ///5126.5938,8444.857,100,0,11,161
        ///5144,9164,100,0,26,153
        ///8304,10176,100,0,35,148
        ///3346,7692,100,0,14,138
        ///6608,4706,100,0,33,134
        ///8172,6298,100,0,19,128
        ///2964,9002,100,0,11,124
        ///10380,3022,100,0,11,119
        ///6302,10152,100,0,18,104
        ///10032,7800,100,0,19,103
        ///11554,7072,100,0,11,103
        ///8612,4658,100,0,14,79
        ///.
        /// </summary>
        public static string wards_Order_Control_201 {
            get {
                return ResourceManager.GetString("wards_Order_Control_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8228,10188,100,0,16,180
        ///5266,9158,100,0,14,169
        ///6610,4648,100,0,17,128
        ///9420,5664,100,0,22,123
        ///8516,4832,100,0,15,114
        ///6332,8152,100,0,11,107
        ///.
        /// </summary>
        public static string wards_Order_Control_25 {
            get {
                return ResourceManager.GetString("wards_Order_Control_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Control_30 {
            get {
                return ResourceManager.GetString("wards_Order_Control_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Control_35 {
            get {
                return ResourceManager.GetString("wards_Order_Control_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11700,5904,100,0,16,249
        ///9420,5658,100,0,93,179
        ///5198,9164,100,0,41,142
        ///11742,3962,100,0,87,135
        ///8088,6190,100,0,44,126
        ///8550,4806,100,0,23,124
        ///2978,10972,100,0,20,113
        ///6308,10120,100,0,14,101
        ///10286,2890,100,0,161,95
        ///2870,11350,100,0,16,94
        ///6306,8156,100,0,19,80
        ///.
        /// </summary>
        public static string wards_Order_Control_5 {
            get {
                return ResourceManager.GetString("wards_Order_Control_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8320,10238,100,1,27,146
        ///12856,1830,100,1,38,139
        ///9392,5642,100,1,42,114
        ///12386,1438,100,1,23,111
        ///2934,11320,100,1,25,94
        ///8100,6238,100,1,28,93
        ///5300,9178,100,1,18,93
        ///11820,4072,100,1,40,93
        ///11890,3724,100,1,42,75
        ///13502,2496,100,1,15,68
        ///3132,10806,100,1,13,68
        ///4398,11736,100,1,13,54
        ///10264,2906,100,1,14,43
        ///6470,8212,100,1,19,39
        ///.
        /// </summary>
        public static string wards_Order_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8320,10238,100,1,27,146
        ///12856,1830,100,1,38,139
        ///9392,5642,100,1,42,114
        ///12386,1438,100,1,23,111
        ///2934,11320,100,1,25,94
        ///8100,6238,100,1,28,93
        ///5300,9178,100,1,18,93
        ///11820,4072,100,1,40,93
        ///11890,3724,100,1,42,75
        ///13502,2496,100,1,15,68
        ///3132,10806,100,1,13,68
        ///4398,11736,100,1,13,54
        ///10264,2906,100,1,14,43
        ///6470,8212,100,1,19,39
        ///.
        /// </summary>
        public static string wards_Order_Regular_01 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11522,7128,100,1,29,155
        ///9670.658,6897.3477,100,1,21,142
        ///12009.036,4653.099,100,1,11,138
        ///11914,3640,100,1,48,134
        ///11742,5916,100,1,49,132
        ///8188,10194,100,1,23,129
        ///12675.916,4902.748,100,1,57,128
        ///9518,5586,100,1,50,117
        ///10014,7748,100,1,19,117
        ///9154.809,7044.3906,100,1,25,112
        ///11378.133,3108.6973,100,1,12,111
        ///11760,3992,100,1,398,109
        ///9672,6352,100,1,37,102
        ///5256,9208,100,1,27,102
        ///10075.463,3898.7192,100,1,15,101
        ///8248,6420,100,1,22,99
        ///9288,2122,100,1,15,98
        ///10364,3136,100,1,30,97
        ///11813. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_10 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11522,7128,100,1,29,155
        ///9670.658,6897.3477,100,1,21,142
        ///12009.036,4653.099,100,1,11,138
        ///11914,3640,100,1,48,134
        ///11742,5916,100,1,49,132
        ///8188,10194,100,1,23,129
        ///12675.916,4902.748,100,1,57,128
        ///9518,5586,100,1,50,117
        ///10014,7748,100,1,19,117
        ///9154.809,7044.3906,100,1,25,112
        ///11378.133,3108.6973,100,1,12,111
        ///11760,3992,100,1,398,109
        ///9672,6352,100,1,37,102
        ///5256,9208,100,1,27,102
        ///10075.463,3898.7192,100,1,15,101
        ///8248,6420,100,1,22,99
        ///9288,2122,100,1,15,98
        ///10364,3136,100,1,30,97
        ///11813. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_101 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11823.938,6536.563,100,1,11,201
        ///8909.059,7240.035,100,1,13,170
        ///11115.898,6098.8633,100,1,12,168
        ///8310,10276,100,1,63,158
        ///11862,7464,100,1,15,157
        ///11716,5964,100,1,37,147
        ///4898,8364,100,1,17,144
        ///7922.176,9295.058,100,1,19,133
        ///6922,8938,100,1,12,131
        ///9523.325,6951.366,100,1,25,128
        ///9794,6414,100,1,45,127
        ///11532,7184,100,1,27,125
        ///9164.137,7051.2227,100,1,50,121
        ///8022,6220,100,1,91,121
        ///8554,6558,100,1,14,121
        ///9850.076,7947.1113,100,1,14,121
        ///12282,1396,100,1,16,120
        ///7892,11782,100,1,21,116
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_15 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5174.37,10010.529,100,1,14,216
        ///9773.117,6909.1777,100,1,13,184
        ///3422,7750,100,1,20,183
        ///8332,6452,100,1,14,163
        ///11760,5868,100,1,23,160
        ///8280,10200,100,1,103,158
        ///7068,3128,100,1,14,157
        ///7782,11798,100,1,13,155
        ///9323.016,6991.5313,100,1,16,154
        ///5240,9090,100,1,77,149
        ///11570,7156,100,1,25,143
        ///9450,5724,100,1,41,141
        ///6782,8998,100,1,14,139
        ///6310,10102,100,1,76,134
        ///10230,2878,100,1,17,130
        ///9824,6526,100,1,26,128
        ///8532,4722,100,1,29,123
        ///7071.748,8707.418,100,1,16,116
        ///4914,8412,100,1,13,115
        ///815 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_20 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5174.37,10010.529,100,1,14,216
        ///9773.117,6909.1777,100,1,13,184
        ///3422,7750,100,1,20,183
        ///8332,6452,100,1,14,163
        ///11760,5868,100,1,23,160
        ///8280,10200,100,1,103,158
        ///7068,3128,100,1,14,157
        ///7782,11798,100,1,13,155
        ///9323.016,6991.5313,100,1,16,154
        ///5240,9090,100,1,77,149
        ///11570,7156,100,1,25,143
        ///9450,5724,100,1,41,141
        ///6782,8998,100,1,14,139
        ///6310,10102,100,1,76,134
        ///10230,2878,100,1,17,130
        ///9824,6526,100,1,26,128
        ///8532,4722,100,1,29,123
        ///7071.748,8707.418,100,1,16,116
        ///4914,8412,100,1,13,115
        ///815 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_201 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5182,9050,100,1,21,218
        ///8224,10238,100,1,48,157
        ///8152,6236,100,1,51,151
        ///6198,8106,100,1,25,151
        ///3336,7740,100,1,13,149
        ///7084,3062,100,1,12,137
        ///9800,6452,100,1,12,137
        ///5048,8518,100,1,19,136
        ///9324,5646,100,1,21,135
        ///6534,4670,100,1,47,127
        ///6312,10098,100,1,28,124
        ///11466,7156,100,1,12,92
        ///9912.773,7799.8335,100,1,15,88
        ///8562,4822,100,1,13,86
        ///5698,3496,100,1,16,85
        ///.
        /// </summary>
        public static string wards_Order_Regular_25 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8302,10226,100,1,24,214
        ///5214,9138,100,1,19,145
        ///9372,5642,100,1,20,128
        ///9946,6576,100,1,12,101
        ///6288,10094,100,1,14,96
        ///.
        /// </summary>
        public static string wards_Order_Regular_30 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Regular_35 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///.
        /// </summary>
        public static string wards_Order_Regular_40 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11838,5926,100,1,23,163
        ///8270,10142,100,1,23,124
        ///11940,3646,100,1,68,114
        ///11609.051,5159.01,100,1,14,108
        ///12258,1322,100,1,76,102
        ///9406,5688,100,1,80,95
        ///8146,6236,100,1,93,94
        ///12942,1902,100,1,76,91
        ///13494,2638,100,1,52,88
        ///9702,6304,100,1,16,86
        ///9916,6542,100,1,15,85
        ///12630,4908,100,1,20,84
        ///10278,2906,100,1,35,84
        ///11938,4832,100,1,11,81
        ///7792,7760,100,1,15,74
        ///3094,10828,100,1,43,69
        ///8406,6448,100,1,26,66
        ///2826,11284,100,1,51,66
        ///1234,12066,100,1,12,65
        ///4192,11860,100,1,49,64
        ///6652,8390,100,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_5 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_5", resourceCulture);
            }
        }
    }
}
