//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoWard.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4140,8000,200,1,1,746
        ///9320,5654,200,1,1,686
        ///12008,10250,100,1,1,654
        ///7064,3124,200,1,1,574
        ///11870,3614,200,1,1,555
        ///9438,5632,100,1,1,539
        ///11600,7074,200,1,1,503
        ///4936.904,8285.651,100,1,1,468
        ///8090,6262,100,1,1,449
        ///11432,4828,200,1,1,435
        ///11923.883,6506.8516,100,1,1,423
        ///10154,4766,200,0,1,416
        ///3422,7750,100,1,1,406
        ///9371.785,4657.649,100,1,1,404
        ///6522,4634,100,1,1,394
        ///3916,7976,200,2,1,370
        ///11423.669,7504.1406,200,1,1,362
        ///6548,8310,100,1,1,352
        ///11942,5916,200,1,1,352
        ///9194,3854,200,1,1,34 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards {
            get {
                return ResourceManager.GetString("wards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11870,3614,200,3,1,555
        ///9194,3854,200,3,1,346
        ///12586,1344,200,3,1,319
        ///8216,6242,200,3,1,213
        ///13562,2830,200,3,1,210
        ///3790,12974,200,3,1,205
        ///12964,1918,200,3,1,191
        ///10668,3444,200,3,1,187
        ///13534,2636,200,3,3,164
        ///6472,8280,200,3,1,156
        ///13460,2628,200,3,2,150
        ///11043.873,2305.3354,200,3,1,138
        ///11826,3828,200,3,2,133
        ///11904,3774,200,3,2,133
        ///10328,4452,200,3,1,122
        ///10476,3122,200,3,1,122
        ///11784,3972,200,3,2,109
        ///11660,2382,200,3,1,105
        ///13562,2658,200,3,2,105
        ///8512,4912,200,3,1,103
        ///8524,6568,200,3, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11432,4828,200,3,1,435
        ///12296,1346,200,3,1,271
        ///11958,3682,200,3,1,263
        ///11602,7062,200,3,3,239
        ///11550,7072,200,3,3,239
        ///11600,7074,200,3,3,239
        ///5985.055,12769.724,200,3,2,220
        ///5988,12762,200,3,2,220
        ///5220,9186,200,3,1,203
        ///11844,3926,200,3,3,201
        ///11832,3848,200,3,3,201
        ///11888,3900,200,3,3,201
        ///12532,1466,200,3,1,196
        ///12114,4676,200,3,1,185
        ///11085.316,2165.1875,200,3,1,173
        ///11720,4078,200,3,1,152
        ///8308,6302,200,3,2,143
        ///8362,6358,200,3,2,143
        ///10110,4608,200,3,2,139
        ///10074,4630,200,3,2,139
        ///11750,3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4140,8000,200,3,1,746
        ///7064,3124,200,3,1,574
        ///10154,4766,200,3,1,416
        ///3916,7976,200,3,1,370
        ///9354,5632,200,3,3,364
        ///9388,5626,200,3,3,364
        ///9320,5654,200,3,3,364
        ///11423.669,7504.1406,200,3,1,362
        ///9384,11396,200,3,1,334
        ///11940.711,5931.716,200,3,2,313
        ///11942,5916,200,3,2,313
        ///8450,6422,200,3,1,308
        ///6104,7046,200,3,1,281
        ///7830,3286,200,3,1,260
        ///3140.565,5811.46,200,3,1,257
        ///11640,5706,200,3,1,219
        ///9810,11044,200,3,1,205
        ///7156,6562,200,3,1,199
        ///5017.5938,2508.4155,200,3,1,196
        ///9824,6440,200,3,1,173
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5984,12768,200,3,1,233
        ///8242,10308,200,3,1,129
        ///9340,11438,200,3,1,117
        ///.
        /// </summary>
        public static string wards_Chaos_All_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5832,12852,200,2,1,57
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3916,7976,200,2,1,370
        ///7830,3286,200,2,1,260
        ///4704,7162,200,2,1,123
        ///6654,3174,200,2,1,102
        ///6504,4822,200,2,1,84
        ///6578,4720,200,2,2,64
        ///6534,4696,200,2,2,64
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8216,6242,200,0,1,213
        ///11784,3972,200,0,1,157
        ///11826,3828,200,0,2,133
        ///11904,3774,200,0,2,133
        ///8524,6568,200,0,1,98
        ///3010,10970,200,0,1,94
        ///6754,8494,200,0,1,40
        ///.
        /// </summary>
        public static string wards_Chaos_Control_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11888,3900,200,0,1,280
        ///11958,3682,200,0,1,263
        ///5220,9186,200,0,1,203
        ///11720,4078,200,0,1,152
        ///10110,4608,200,0,2,139
        ///10074,4630,200,0,2,139
        ///11750,3974,200,0,1,128
        ///11854,5812,200,0,1,125
        ///6658,4692,200,0,1,123
        ///8574,6576,200,0,1,121
        ///3064,9056,200,0,1,118
        ///11550,7072,200,0,2,107
        ///11602,7062,200,0,2,107
        ///9438,5632,200,0,3,106
        ///9484,5584,200,0,3,106
        ///9478,5620,200,0,3,106
        ///10372,3080,200,0,1,89
        ///6744,8404,200,0,1,82
        ///4416,11810,200,0,1,82
        ///10590,3326,200,0,1,71
        ///6638,8408,200,0,1,65
        ///12500,5054,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10154,4766,200,0,1,416
        ///11940.711,5931.716,200,0,1,275
        ///6898,3042,200,0,1,171
        ///9890,4752,200,0,1,164
        ///6526,4678,200,0,1,163
        ///7936,3564,200,0,1,162
        ///6730,3110,200,0,1,95
        ///5008,10162,200,0,1,55
        ///3070,9012,200,0,1,54
        ///5144,9122,200,0,3,52
        ///5182,9092,200,0,3,52
        ///5242,9128,200,0,3,52
        ///7610,6978,200,0,1,51
        ///5410,3312,200,0,1,21
        ///6758,8484,200,0,1,7
        ///.
        /// </summary>
        public static string wards_Chaos_Control_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11870,3614,200,1,1,555
        ///9194,3854,200,1,1,346
        ///12586,1344,200,1,1,319
        ///13562,2830,200,1,1,210
        ///3790,12974,200,1,1,205
        ///12964,1918,200,1,1,191
        ///10668,3444,200,1,1,187
        ///13534,2636,200,1,3,164
        ///6472,8280,200,1,1,156
        ///13460,2628,200,1,2,150
        ///11043.873,2305.3354,200,1,1,138
        ///10328,4452,200,1,1,122
        ///10476,3122,200,1,1,122
        ///13562,2658,200,1,2,105
        ///11660,2382,200,1,1,105
        ///8512,4912,200,1,1,103
        ///6600,8366,200,1,2,98
        ///6552,8360,200,1,2,98
        ///3754,9742,200,1,1,83
        ///3508,7726,200,1,1,79
        ///6354,8162,200,1,1,72
        ///68 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11600,7074,200,1,1,503
        ///11432,4828,200,1,1,435
        ///12296,1346,200,1,1,271
        ///5985.055,12769.724,200,1,2,220
        ///5988,12762,200,1,2,220
        ///12532,1466,200,1,1,196
        ///12114,4676,200,1,1,185
        ///11085.316,2165.1875,200,1,1,173
        ///11844,3926,200,1,2,162
        ///11832,3848,200,1,2,162
        ///10336,3110,200,1,1,148
        ///8362,6358,200,1,2,143
        ///8308,6302,200,1,2,143
        ///10923.592,9161.074,200,1,1,126
        ///9476,5606,200,1,4,115
        ///9772.919,6458.0254,200,1,1,114
        ///10304,4832,200,1,1,107
        ///4920,8406,200,1,1,103
        ///10626,3012,200,1,2,103
        ///10554,2996,200, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_10 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4140,8000,200,1,1,746
        ///7064,3124,200,1,1,574
        ///9388,5626,200,1,3,364
        ///9354,5632,200,1,3,364
        ///9320,5654,200,1,3,364
        ///11423.669,7504.1406,200,1,1,362
        ///11942,5916,200,1,1,352
        ///9384,11396,200,1,1,334
        ///8450,6422,200,1,1,308
        ///6104,7046,200,1,1,281
        ///3140.565,5811.46,200,1,1,257
        ///11640,5706,200,1,1,219
        ///9810,11044,200,1,1,205
        ///7156,6562,200,1,1,199
        ///5017.5938,2508.4155,200,1,1,196
        ///7908,3480,200,1,1,174
        ///9824,6440,200,1,1,173
        ///5925.7773,7665.537,200,1,1,172
        ///11326,7612,200,1,1,158
        ///12790.232,6411.243,200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_20 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5984,12768,200,1,1,233
        ///8242,10308,200,1,1,129
        ///9340,11438,200,1,1,117
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///12338,1356,100,3,1,313
        ///9746,6414,100,3,1,283
        ///12896,1870,100,3,2,210
        ///12898,1896,100,3,2,210
        ///11866,3770,100,3,1,187
        ///13460,2710,100,3,2,187
        ///13462,2780,100,3,2,187
        ///11764,4034,100,3,4,179
        ///13534,2636,100,3,2,170
        ///13604,2592,100,3,2,170
        ///11155.695,5911.732,100,3,1,166
        ///11794,4054,100,3,5,159
        ///11816,4042,100,3,5,159
        ///11824,4018,100,3,5,159
        ///11834,4116,100,3,4,151
        ///10310,4740,100,3,1,126
        ///12168,1312,100,3,1,126
        ///9474,5656,100,3,1,121
        ///10450,2944,100,3,1,111
        ///9373.678,4207.3643,100,3,1,90
        ///6296,809 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_0 {
            get {
                return ResourceManager.GetString("wards_Order_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9371.785,4657.649,100,3,1,404
        ///10700,4590,100,3,1,332
        ///9498,5616,100,3,3,307
        ///9438,5632,100,3,3,307
        ///9478,5578,100,3,3,307
        ///11960.31,4709.6885,100,3,1,297
        ///11072,4702,100,3,1,262
        ///7330.589,12711.268,100,3,1,257
        ///10528,4696,100,3,1,255
        ///6544,4730,100,3,1,245
        ///13442,2470,100,3,1,234
        ///6548,8310,100,3,2,214
        ///10562,5122,100,3,1,205
        ///5746,12714,100,3,1,194
        ///8480,6524,100,3,2,191
        ///8412,6482,100,3,2,191
        ///6175.918,8097.7173,100,3,1,181
        ///10480.486,4353.7,100,3,1,176
        ///11948,5780,100,3,1,175
        ///8090,6262,100, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_10 {
            get {
                return ResourceManager.GetString("wards_Order_All_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///12008,10250,100,3,1,654
        ///4936.904,8285.651,100,3,1,468
        ///11923.883,6506.8516,100,3,1,423
        ///3422,7750,100,3,1,406
        ///4730,7176,100,3,1,317
        ///10262,8986,100,3,1,308
        ///9874,6456,100,3,1,301
        ///9370,5642,100,3,1,232
        ///6594,4694,100,3,3,230
        ///6510,4684,100,3,3,230
        ///6522,4634,100,3,3,230
        ///6312,10102,100,3,1,167
        ///7566,6654,100,3,1,158
        ///12196,1380,100,3,1,140
        ///12790.363,6304.881,100,3,1,137
        ///8290,5216,100,3,1,137
        ///6358.431,7953.3306,100,3,1,123
        ///7457.25,2243.3293,100,3,1,122
        ///9860,7238,100,3,1,121
        ///8286,10146,100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_20 {
            get {
                return ResourceManager.GetString("wards_Order_All_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5746,12714,100,2,1,194
        ///11948,5780,100,2,1,175
        ///8158,10088,100,2,1,131
        ///7044,11304,100,2,1,121
        ///4368,11908,100,2,1,47
        ///.
        /// </summary>
        public static string wards_Order_Blue_10 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10262,8986,100,2,1,308
        ///9874,6456,100,2,1,301
        ///6594,4694,100,2,1,104
        ///11918,11036,100,2,1,100
        ///10028,8042,100,2,1,84
        ///9952,7606,100,2,1,79
        ///11768,5796,100,2,1,60
        ///11922,11314,100,2,1,57
        ///14102,14410,100,2,1,30
        ///.
        /// </summary>
        public static string wards_Order_Blue_20 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9746,6414,100,0,1,283
        ///10310,4740,100,0,1,126
        ///9474,5656,100,0,1,121
        ///10450,2944,100,0,1,111
        ///11816,4042,100,0,1,104
        ///8140,6194,100,0,1,101
        ///9373.678,4207.3643,100,0,1,90
        ///10314,2968,100,0,1,23
        ///.
        /// </summary>
        public static string wards_Order_Control_0 {
            get {
                return ResourceManager.GetString("wards_Order_Control_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9478,5578,100,0,1,298
        ///6544,4730,100,0,1,245
        ///10562,5122,100,0,1,205
        ///10582,3052,100,0,2,188
        ///10619.881,3007.023,100,0,2,188
        ///10410,3030,100,0,1,187
        ///6175.918,8097.7173,100,0,1,181
        ///10480.486,4353.7,100,0,1,176
        ///3040,10794,100,0,1,161
        ///2856,11268,100,0,1,127
        ///12373.742,7259.258,100,0,1,112
        ///11790,3876,100,0,2,104
        ///11816,3864,100,0,2,104
        ///3278,7826,100,0,1,101
        ///8254,6316,100,0,1,81
        ///6456,8252,100,0,2,69
        ///6520,8280,100,0,2,69
        ///9700.465,3907.862,100,0,1,68
        ///11864,4006,100,0,2,66
        ///11790,4006,100,0,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_10 {
            get {
                return ResourceManager.GetString("wards_Order_Control_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4730,7176,100,0,1,317
        ///9370,5642,100,0,1,232
        ///9322,11470,100,0,1,139
        ///10332,3202,100,0,1,106
        ///6950,11442,100,0,1,50
        ///3038,9026,100,0,1,30
        ///8596,4702,100,0,1,5
        ///9918,6556,100,0,1,3
        ///.
        /// </summary>
        public static string wards_Order_Control_20 {
            get {
                return ResourceManager.GetString("wards_Order_Control_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///12338,1356,100,1,1,313
        ///12896,1870,100,1,2,210
        ///12898,1896,100,1,2,210
        ///11764,4034,100,1,3,205
        ///13462,2780,100,1,2,187
        ///13460,2710,100,1,2,187
        ///11866,3770,100,1,1,187
        ///11794,4054,100,1,4,172
        ///11824,4018,100,1,4,172
        ///13604,2592,100,1,2,170
        ///13534,2636,100,1,2,170
        ///11834,4116,100,1,3,167
        ///11155.695,5911.732,100,1,1,166
        ///12168,1312,100,1,1,126
        ///6276,8090,100,1,2,85
        ///6296,8098,100,1,2,85
        ///4342,11906,100,1,1,77
        ///6494,8328,100,1,1,70
        ///2532,13624,100,1,2,64
        ///2594,13658,100,1,2,64
        ///10162,7470,100,1,1,49
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9371.785,4657.649,100,1,1,404
        ///6548,8310,100,1,1,352
        ///11790,4048,100,1,1,340
        ///10700,4590,100,1,1,332
        ///9498,5616,100,1,2,311
        ///9438,5632,100,1,2,311
        ///11960.31,4709.6885,100,1,1,297
        ///11072,4702,100,1,1,262
        ///7330.589,12711.268,100,1,1,257
        ///10528,4696,100,1,1,255
        ///13442,2470,100,1,1,234
        ///8480,6524,100,1,2,191
        ///8412,6482,100,1,2,191
        ///8056,6220,100,1,4,173
        ///8054,6218,100,1,4,173
        ///8090,6262,100,1,4,173
        ///8072,6180,100,1,4,173
        ///9980,6552,100,1,1,160
        ///7824.7236,9301.434,100,1,1,142
        ///8734,6682,100,1,1,142
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_10 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///12008,10250,100,1,1,654
        ///4936.904,8285.651,100,1,1,468
        ///11923.883,6506.8516,100,1,1,423
        ///3422,7750,100,1,1,406
        ///6522,4634,100,1,2,293
        ///6510,4684,100,1,2,293
        ///6312,10102,100,1,1,167
        ///7566,6654,100,1,1,158
        ///12196,1380,100,1,1,140
        ///8290,5216,100,1,1,137
        ///12790.363,6304.881,100,1,1,137
        ///6358.431,7953.3306,100,1,1,123
        ///7457.25,2243.3293,100,1,1,122
        ///9860,7238,100,1,1,121
        ///8286,10146,100,1,1,120
        ///8050,3492,100,1,2,93
        ///8056,3494,100,1,2,93
        ///10774,7562,100,1,1,79
        ///5232,9070,100,1,1,76
        ///9364,11434,100,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_20 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_20", resourceCulture);
            }
        }
    }
}
