//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoWard.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8041.1777,4277.3423,200,3,81,313
        ///8092,3404,200,3,17,237
        ///6888,11468,200,3,12,233
        ///11502,7142,200,3,16,169
        ///7022,3048,200,3,12,150
        ///3380,7780,200,3,20,142
        ///10248,2970,200,3,13,123
        ///7021.0874,5630.438,200,3,19,114
        ///5284,9152,200,3,94,82
        ///9388,5744,200,3,35,80
        ///6892,8630,200,3,20,69
        ///8222,10238,200,3,13,39
        ///12030.219,3760.8164,200,3,16,38
        ///12976,1898,200,3,16,32
        ///13566,2818,200,3,30,27
        ///.
        /// </summary>
        public static string wards_Chaos_All_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8424,2926,200,3,15,126
        ///11478.047,4957.9014,200,3,20,124
        ///3276,7806,200,3,108,120
        ///9838.209,2758.1895,200,3,23,115
        ///10526,5044,200,3,16,112
        ///7832,3570,200,3,123,105
        ///9532,5528,200,3,71,105
        ///11552,7138,200,3,166,98
        ///7185.08,5356.0303,200,3,11,98
        ///9728,6328,200,3,254,90
        ///9310,2156,200,3,143,89
        ///8594,4826,200,3,864,87
        ///11076.477,2158.2773,200,3,61,86
        ///7790,774,200,3,17,86
        ///11870.23,5956.8794,200,3,153,85
        ///7931.076,5965.256,200,3,121,84
        ///10606,2986,200,3,1047,83
        ///11790,3922,200,3,651,82
        ///5116,8570, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_12 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8827.246,1728.5352,200,3,15,129
        ///11000,4330,200,3,27,117
        ///3412,7750,200,3,91,116
        ///11818,5740,200,3,28,110
        ///2784,7244,200,3,20,103
        ///6528,4660,200,3,487,102
        ///6972.3735,5627.381,200,3,104,101
        ///9376,5718,200,3,580,98
        ///10102,4690,200,3,187,98
        ///3066,9016,200,3,182,98
        ///5194,9200,200,3,322,97
        ///11558,7068,200,3,218,96
        ///7882.383,6007.81,200,3,109,96
        ///9226,3864,200,3,65,95
        ///7034,6894,200,3,19,95
        ///8644,4550,200,3,48,94
        ///8578,6520,200,3,161,83
        ///11808,4052,200,3,348,82
        ///5623.1655,7854.627,200,3,54,82
        ///4752,72 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6322,5326,200,3,32,120
        ///7473.6953,5214.4395,200,3,20,120
        ///10581.605,5812.3105,200,3,63,119
        ///9426,5680,200,3,981,117
        ///2940,9050,200,3,61,115
        ///6972.147,3123.3665,200,3,118,104
        ///8544,4882,200,3,474,103
        ///3781.745,8758.875,200,3,25,103
        ///5122,8548,200,3,153,102
        ///4938.0386,7108.589,200,3,135,102
        ///5506,3358,200,3,91,101
        ///8025.8213,4262.503,200,3,29,100
        ///5846,7712,200,3,29,100
        ///11510,7180,200,3,234,99
        ///7744,11762,200,3,50,99
        ///8164,3426,200,3,39,95
        ///10240,4444,200,3,33,95
        ///9220.348,3857.2344,200,3,83,93 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_18 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5072.536,10970.76,200,3,51,143
        ///10187.668,4873.092,200,3,37,139
        ///4804,10180,200,3,100,124
        ///9502,5674,200,3,444,120
        ///7180.2266,5456.247,200,3,18,116
        ///5623.8877,3509.687,200,3,92,115
        ///6564,4628,200,3,346,114
        ///8694,4538,200,3,31,114
        ///5266,9212,200,3,421,113
        ///2990,6162,200,3,18,111
        ///4796,7226,200,3,155,110
        ///11770,5750,200,3,21,106
        ///4914,8428,200,3,203,105
        ///11530,7154,200,3,208,103
        ///3112,8972,200,3,153,103
        ///6824.0894,3154.9097,200,3,143,102
        ///6514,9996,200,3,19,100
        ///9926,4030,200,3,34,93
        ///10723.472,5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_21 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7158,5476,200,3,19,173
        ///9992,4026,200,3,31,137
        ///8286,5820,200,3,14,135
        ///3386,7804,200,3,80,125
        ///5072.6074,8448.682,200,3,113,122
        ///10234.055,4801.634,200,3,44,116
        ///6494,4720,200,3,256,115
        ///7874,3532,200,3,77,115
        ///9370,5670,200,3,327,110
        ///7104,3096,200,3,67,108
        ///4806,10160,200,3,77,106
        ///8544,4764,200,3,264,105
        ///5633.9453,3485.134,200,3,89,102
        ///10572.578,5807.3223,200,3,46,99
        ///9722,6394,200,3,201,98
        ///11878,5930,200,3,91,98
        ///4858,7164,200,3,129,97
        ///11462,7176,200,3,110,97
        ///10560,3096,200,3,51,91
        ///70 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_24 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5230.502,10929.133,200,3,14,181
        ///4812,10058,200,3,17,148
        ///3058,7354,200,3,13,148
        ///5848,12746,200,3,17,139
        ///4754,6986,200,3,26,138
        ///7024,11376,200,3,20,128
        ///5228,9160,200,3,274,123
        ///9672,6302,200,3,33,119
        ///8154,5856,200,3,18,116
        ///11770,3900,200,3,13,115
        ///5452,3462,200,3,52,113
        ///7024.918,5621.537,200,3,34,109
        ///8506,4864,200,3,178,105
        ///6490,4774,200,3,90,103
        ///11620,7142,200,3,64,94
        ///6788,3048,200,3,37,91
        ///4886,8414,200,3,90,90
        ///6306,10118,200,3,130,85
        ///6895.754,8606.181,200,3,172,84
        ///7802,11752,200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_27 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9162,2122,200,3,13,110
        ///6626,4714,200,3,91,102
        ///11977.23,5757.339,200,3,28,95
        ///9416,5682,200,3,285,90
        ///11870,3904,200,3,139,80
        ///6973.1094,5615.4556,200,3,49,79
        ///9758.736,6458.497,200,3,31,79
        ///10610,3092,200,3,461,77
        ///3124,10866,200,3,254,65
        ///4480,11784,200,3,36,63
        ///6296,10136,200,3,22,62
        ///8314,6318,200,3,33,60
        ///4768,7244,200,3,11,52
        ///6887.8877,8606.564,200,3,194,49
        ///12222,1360,200,3,158,48
        ///12980,1952,200,3,150,48
        ///.
        /// </summary>
        public static string wards_Chaos_All_3 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5474,10386,200,3,60,156
        ///10590,5794,200,3,18,137
        ///5278.598,7980.9536,200,3,30,132
        ///9326,5666,200,3,42,123
        ///7038,3120,200,3,38,119
        ///4884.1475,7159.352,200,3,54,116
        ///6558,4702,200,3,165,115
        ///5242,9096,200,3,129,112
        ///5523.3906,3307.5488,200,3,13,108
        ///8630,4518,200,3,11,98
        ///10402,3082,200,3,29,88
        ///9868,6564,200,3,32,82
        ///8302,10186,200,3,122,80
        ///6978.8516,5622.6104,200,3,24,75
        ///9182,11420,200,3,24,75
        ///7824,11828,200,3,22,74
        ///3072,10818,200,3,19,69
        ///9978,7834,200,3,53,67
        ///6283.561,10301.932,200,3,44, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3480,7766,200,3,11,208
        ///9778,6456,200,3,24,142
        ///5000,8472,200,3,19,134
        ///4842,7116,200,3,23,126
        ///6893.307,3156.3008,200,3,11,120
        ///6568,4688,200,3,75,118
        ///8232,10262,200,3,43,114
        ///11524.15,7211.742,200,3,17,109
        ///9460,5706,200,3,56,98
        ///8528,4892,200,3,23,93
        ///6268,10050,200,3,11,84
        ///3102,8988,200,3,11,35
        ///.
        /// </summary>
        public static string wards_Chaos_All_33 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5272,9194,200,3,15,126
        ///4814,7118,200,3,11,116
        ///9706,6358,200,3,11,108
        ///8280,10286,200,3,13,79
        ///.
        /// </summary>
        public static string wards_Chaos_All_36 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10494.137,4408.6626,200,3,30,175
        ///3084,8974,200,3,69,135
        ///7124,3110,200,3,22,102
        ///9480,5632,200,3,475,99
        ///6654,4698,200,3,58,97
        ///7874,3514,200,3,50,97
        ///5252,9200,200,3,155,91
        ///10438,3038,200,3,252,89
        ///8386,5732,200,3,36,87
        ///4700,7172,200,3,21,85
        ///5274.838,7976.1787,200,3,19,84
        ///11784,3992,200,3,849,83
        ///6824.0884,5608.9917,200,3,30,82
        ///8556,4782,200,3,265,81
        ///6332,10056,200,3,33,79
        ///11934,5884,200,3,60,76
        ///9788,6410,200,3,81,73
        ///4660,12008,200,3,60,73
        ///8566,6624,200,3,248,71
        ///13500,2562,200,3,98, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_6 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3256,7794,200,3,57,105
        ///10156,4764,200,3,58,91
        ///6527.7607,4858.0103,200,3,13,91
        ///11062,2130,200,3,56,90
        ///9350,5682,200,3,404,89
        ///8562,4834,200,3,406,87
        ///7102,3054,200,3,32,83
        ///4738,7128,200,3,36,82
        ///9322,2192,200,3,81,81
        ///8272,5738,200,3,49,78
        ///11828.042,6007.2993,200,3,51,76
        ///7026.1406,5619.177,200,3,46,75
        ///5206,8526,200,3,41,75
        ///10568,2990,200,3,930,74
        ///4542,11722,200,3,40,74
        ///5504,12744,200,3,12,72
        ///7922,3528,200,3,38,71
        ///8650,6662,200,3,220,68
        ///3048,11050,200,3,172,68
        ///9758,6482,200,3,76,67
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_All_9 {
            get {
                return ResourceManager.GetString("wards_Chaos_All_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8510,4888,200,2,11,50
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_12 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11578,7124,200,2,16,97
        ///8510,4814,200,2,37,78
        ///10364,2976,200,2,20,70
        ///6586,4662,200,2,57,67
        ///9806,6454,200,2,15,66
        ///9408,5658,200,2,35,59
        ///8580,6562,200,2,14,36
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7058,3154,200,2,15,102
        ///11526,7098,200,2,22,97
        ///6634,4738,200,2,42,95
        ///3364,7698,200,2,21,89
        ///9776,6482,200,2,24,88
        ///8340,6316,200,2,11,85
        ///5326,10344,200,2,13,84
        ///5584,3538,200,2,12,79
        ///9362,5632,200,2,36,78
        ///3148,10854,200,2,21,69
        ///10378,3172,200,2,17,66
        ///8023.923,3507.8806,200,2,13,66
        ///8180,10246,200,2,23,63
        ///9326,2156,200,2,13,57
        ///9988,7834,200,2,36,56
        ///4452,11822,200,2,16,56
        ///12564,5176,200,2,15,51
        ///6212,10102,200,2,14,43
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_18 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3274,7752,200,2,22,135
        ///5202,10734,200,2,16,130
        ///6975.443,3113.8083,200,2,11,104
        ///9752,6354,200,2,29,81
        ///6636,4766,200,2,39,73
        ///8584,4756,200,2,58,72
        ///4754,7184,200,2,42,71
        ///10022,7864,200,2,37,66
        ///5080,8568,200,2,24,63
        ///11798,5908,200,2,21,63
        ///10300,3058,200,2,27,53
        ///8172,10248,200,2,22,53
        ///12520,5260,200,2,14,50
        ///6428,8194,200,2,17,39
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_21 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3080,8968,200,2,20,120
        ///5004,8484,200,2,14,113
        ///11860,5904,200,2,18,105
        ///11596,7122,200,2,25,96
        ///3426,7776,200,2,32,95
        ///6748,3098,200,2,17,95
        ///7932,11846,200,2,13,88
        ///9918.981,7809.241,200,2,15,85
        ///8540,4828,200,2,29,82
        ///10338,3132,200,2,22,80
        ///8222,10270,200,2,52,70
        ///9836,6444,200,2,21,68
        ///6594,8344,200,2,15,68
        ///6334,10180,200,2,20,67
        ///6620,4708,200,2,39,65
        ///10092,4602,200,2,12,39
        ///12592,5178,200,2,15,24
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_24 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5184,9162,200,2,32,104
        ///8540,4866,200,2,17,89
        ///10086,7892,200,2,12,86
        ///9770.332,6465.708,200,2,20,81
        ///8214,10188,200,2,34,74
        ///8322,6400,200,2,14,54
        ///7896,11850,200,2,11,45
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_27 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9767.106,6463.261,200,2,14,106
        ///6308,10138,200,2,17,101
        ///9450,5608,200,2,19,94
        ///5376,10506,200,2,12,89
        ///6586,4646,200,2,18,82
        ///8262,10308,200,2,26,66
        ///9990,7900,200,2,20,48
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8600,4710,200,2,13,74
        ///.
        /// </summary>
        public static string wards_Chaos_Blue_33 {
            get {
                return ResourceManager.GetString("wards_Chaos_Blue_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3374,7730,200,0,42,121
        ///10156,4802,200,0,27,120
        ///9464,5658,200,0,550,101
        ///8508,4806,200,0,228,97
        ///10344,3030,200,0,69,96
        ///5242,9128,200,0,249,93
        ///11594,7122,200,0,67,93
        ///11930.797,5905.9023,200,0,89,88
        ///4768,7132,200,0,42,86
        ///11892,3814,200,0,164,84
        ///10082,7822,200,0,18,83
        ///8414,6508,200,0,71,81
        ///9234,2102,200,0,20,74
        ///4386,11788,200,0,83,73
        ///3084,10850,200,0,197,72
        ///13078,1966,200,0,31,65
        ///6322,10138,200,0,46,62
        ///2302,9708,200,0,28,61
        ///12630,4860,200,0,80,54
        ///8296,10152,200,0,16,49
        ///13574,2730,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_12 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3304,7802,200,0,92,108
        ///11930,5792,200,0,67,104
        ///3100,9008,200,0,88,103
        ///9426,5662,200,0,550,102
        ///5246,9136,200,0,302,100
        ///7054,3178,200,0,31,99
        ///10134,4572,200,0,61,97
        ///6580,4778,200,0,69,94
        ///8538,4822,200,0,243,91
        ///11610,7084,200,0,88,90
        ///7966,3448,200,0,13,90
        ///8584,6502,200,0,63,87
        ///6534,8350,200,0,31,87
        ///12314,1352,200,0,12,86
        ///4770,7092,200,0,66,85
        ///3090,10848,200,0,133,78
        ///4490,11890,200,0,75,78
        ///8282,10318,200,0,48,76
        ///10318,3018,200,0,56,74
        ///11888,3870,200,0,91,73
        ///13494,2774,200,0,26,67
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10140,4746,200,0,53,131
        ///5540,3434,200,0,30,128
        ///4864,8334,200,0,24,120
        ///6638,4642,200,0,60,119
        ///7742,11748,200,0,17,117
        ///9400,5664,200,0,393,114
        ///3373.8628,7708.2266,200,0,45,114
        ///5244,9142,200,0,255,113
        ///3080,9008,200,0,81,112
        ///8514,4842,200,0,162,102
        ///6996,3112,200,0,36,101
        ///6560,10012,200,0,11,101
        ///11598,7054,200,0,64,97
        ///7862,3528,200,0,31,97
        ///9759.754,6459.7676,200,0,77,95
        ///4666,11990,200,0,36,94
        ///11782,5918,200,0,69,89
        ///10402,3014,200,0,47,89
        ///9934,7886,200,0,41,87
        ///11878,3992,200,0,63,82 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_18 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5118,8472,200,0,40,137
        ///5614.8687,3491.9822,200,0,20,132
        ///3308,7784,200,0,58,128
        ///6975.0703,3114.924,200,0,26,121
        ///6534,4668,200,0,142,116
        ///9354,5682,200,0,130,113
        ///4742,7164,200,0,70,111
        ///11580,7076,200,0,53,110
        ///10188,4656,200,0,40,109
        ///8478,4900,200,0,42,103
        ///9902,6502,200,0,34,97
        ///3130,9046,200,0,50,95
        ///11686,5886,200,0,13,95
        ///6278,10150,200,0,125,94
        ///10458,3030,200,0,18,89
        ///7898,11832,200,0,18,89
        ///5438,10644,200,0,34,83
        ///8284,10320,200,0,68,80
        ///6786,8504,200,0,95,78
        ///11762,4038,200,0,31,73
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_21 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10022,3928,200,0,16,168
        ///4898,8316,200,0,13,156
        ///6534,4702,200,0,94,141
        ///5482,3466,200,0,19,130
        ///5260,9154,200,0,146,128
        ///11576,7120,200,0,48,126
        ///9526,5554,200,0,25,121
        ///9242,2122,200,0,11,121
        ///9722,6394,200,0,57,109
        ///3324,7762,200,0,32,109
        ///11754,5934,200,0,23,108
        ///5489.2573,10452.965,200,0,28,106
        ///6874,3110,200,0,30,104
        ///7944,3510,200,0,17,96
        ///6728,8532,200,0,55,90
        ///6286,10094,200,0,78,86
        ///10426,3082,200,0,25,80
        ///2974,9030,200,0,17,77
        ///4840,7080,200,0,36,76
        ///8360,10172,200,0,33,76
        ///9842,4764,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_24 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5073.3745,10953.961,200,0,14,171
        ///6883.4287,3166.9487,200,0,11,166
        ///5270,9118,200,0,82,145
        ///9546,5660,200,0,20,130
        ///8540,4828,200,0,48,109
        ///11776,5902,200,0,28,104
        ///6280,10102,200,0,50,100
        ///6828,8548,200,0,37,99
        ///8172,10252,200,0,18,90
        ///3356,7728,200,0,13,90
        ///10020,7802,200,0,28,79
        ///5482,3392,200,0,14,76
        ///2994,9026,200,0,17,68
        ///.
        /// </summary>
        public static string wards_Chaos_Control_27 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10430,3030,200,0,12,91
        ///8506,4882,200,0,48,88
        ///3088,10914,200,0,27,83
        ///9368,5590,200,0,26,82
        ///11788,4036,200,0,95,79
        ///8588,6554,200,0,45,64
        ///.
        /// </summary>
        public static string wards_Chaos_Control_3 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9762,6424,200,0,15,132
        ///4752,7146,200,0,14,130
        ///6620,4688,200,0,20,110
        ///5508,3466,200,0,16,103
        ///9500,5600,200,0,24,98
        ///8340,10202,200,0,28,84
        ///.
        /// </summary>
        public static string wards_Chaos_Control_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9446,5628,200,0,20,104
        ///5248,9172,200,0,20,77
        ///.
        /// </summary>
        public static string wards_Chaos_Control_33 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9456,5664,200,0,383,112
        ///11540,7194,200,0,18,105
        ///4712,7174,200,0,14,104
        ///3026,9060,200,0,26,103
        ///7844,3572,200,0,23,101
        ///6598,4692,200,0,27,100
        ///10184,4720,200,0,36,99
        ///8484,4822,200,0,143,94
        ///5232,9158,200,0,131,94
        ///10646,3012,200,0,62,94
        ///11798,3880,200,0,217,88
        ///3382,7762,200,0,27,88
        ///8640,6566,200,0,91,80
        ///4574,11916,200,0,61,78
        ///11894,5832,200,0,47,73
        ///6290,10128,200,0,24,73
        ///3042,11078,200,0,35,71
        ///9800,6500,200,0,22,62
        ///6588,8354,200,0,23,50
        ///13384,2558,200,0,13,43
        ///12636,4856,200,0,25,42 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_6 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9650,6430,200,0,48,106
        ///11748,5926,200,0,55,105
        ///3122,8952,200,0,53,102
        ///8520,4876,200,0,168,100
        ///9352,2150,200,0,35,97
        ///9434,5642,200,0,1060,96
        ///6604,4744,200,0,56,92
        ///4712,7174,200,0,20,91
        ///7918,3508,200,0,14,87
        ///5192,9208,200,0,118,83
        ///11878,3794,200,0,209,81
        ///8290,10242,200,0,11,80
        ///10530,3060,200,0,132,77
        ///4404,11834,200,0,96,75
        ///4900,8346,200,0,12,75
        ///3128,10834,200,0,190,74
        ///8520,6542,200,0,159,73
        ///12416,1448,200,0,21,63
        ///6696,8480,200,0,77,62
        ///9658,4132,200,0,14,61
        ///6332,10146,200,0,24,58 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Control_9 {
            get {
                return ResourceManager.GetString("wards_Chaos_Control_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///2988,8306,200,1,12,278
        ///7116,3082,200,1,41,238
        ///4125.1704,7958.105,200,1,27,181
        ///6582,4650,200,1,45,123
        ///9372,5700,200,1,38,78
        ///8496,4788,200,1,27,76
        ///10416,3038,200,1,46,72
        ///6254,10200,200,1,12,66
        ///9861.824,6554.6895,200,1,11,40
        ///13072,1988,200,1,45,27
        ///11782,3978,200,1,15,27
        ///12204,1338,200,1,15,27
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8423.762,2912.296,200,1,14,134
        ///9808,2750,200,1,21,111
        ///6594,4710,200,1,239,106
        ///3020.4504,8382.077,200,1,12,106
        ///11566,7104,200,1,82,102
        ///5037.949,8385.273,200,1,18,100
        ///7832,3570,200,1,93,98
        ///9498,5628,200,1,330,96
        ///11992,5734,200,1,87,95
        ///9198,2096,200,1,70,92
        ///9150,3902,200,1,31,91
        ///11028.994,2308.435,200,1,52,90
        ///7742,6020,200,1,35,90
        ///3462,7684,200,1,13,89
        ///10580,3018,200,1,4656,83
        ///11944,4062,200,1,172,82
        ///8568,4810,200,1,375,79
        ///9863.764,6558.8335,200,1,77,76
        ///6278,10154,200,1,28,76
        ///519 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_12 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8474,5692,200,1,12,168
        ///6668,6708,200,1,11,158
        ///3412,7790,200,1,39,129
        ///7194.547,5404.4844,200,1,26,125
        ///2774,7266,200,1,23,115
        ///6520,4686,200,1,330,113
        ///10627.164,5760.5757,200,1,58,113
        ///9426,5666,200,1,564,105
        ///11532,7134,200,1,135,102
        ///2897.151,8432.14,200,1,14,98
        ///5278,9142,200,1,198,95
        ///11974,5788,200,1,85,93
        ///6824.007,3159.898,200,1,82,93
        ///8498,4858,200,1,426,88
        ///5702,3490,200,1,21,87
        ///10028,8060,200,1,19,87
        ///7458.008,2243.9453,200,1,19,85
        ///5626.5977,7862.4023,200,1,54,82
        ///9194,2150,200,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_15 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9472,5724,200,1,271,127
        ///6616,4786,200,1,164,123
        ///8943.001,4964.774,200,1,39,121
        ///10574.262,5808.893,200,1,61,119
        ///7078.87,5624.916,200,1,66,117
        ///10782,4486,200,1,23,110
        ///5278,9174,200,1,265,108
        ///2720,7204,200,1,21,106
        ///7939.401,3558.5105,200,1,56,103
        ///5473.271,7925.979,200,1,99,100
        ///3392,7778,200,1,47,99
        ///9200,3858,200,1,72,97
        ///9873.77,6557.838,200,1,147,93
        ///11552,7102,200,1,154,92
        ///5466,10560,200,1,50,87
        ///6264,10124,200,1,70,86
        ///7771.794,11750.8125,200,1,32,84
        ///10594,3042,200,1,454,83
        ///11648, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_18 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6498,4672,200,1,223,125
        ///5246,9104,200,1,244,120
        ///8250,4756,200,1,13,119
        ///9438,5582,200,1,210,116
        ///7018,3130,200,1,62,115
        ///7892,5988,200,1,88,114
        ///5478.4785,10503.882,200,1,138,113
        ///3280,7772,200,1,77,110
        ///11774,5926,200,1,32,107
        ///4972.627,8343.511,200,1,121,106
        ///2989.3025,6168.0576,200,1,16,102
        ///11522,7078,200,1,63,100
        ///7874,3574,200,1,44,100
        ///5782,12754,200,1,17,97
        ///10635.502,3058.7607,200,1,54,92
        ///8691.408,6757.1167,200,1,85,90
        ///6927.417,5625.004,200,1,66,90
        ///3002,9036,200,1,73,89
        ///6802,8596 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_21 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5470.4404,10508.762,200,1,109,174
        ///2778,7214,200,1,12,130
        ///5302,9146,200,1,160,124
        ///6516,4630,200,1,154,122
        ///8002,3506,200,1,29,115
        ///9300,5704,200,1,32,113
        ///10002,6588,200,1,19,112
        ///5619.38,3502.1335,200,1,58,106
        ///8590,4852,200,1,141,102
        ///5588,7868,200,1,41,102
        ///4884,8398,200,1,116,96
        ///6844,3162,200,1,72,95
        ///4838,7178,200,1,87,94
        ///6836,8602,200,1,291,92
        ///10577.265,5808.9893,200,1,45,92
        ///11931.836,5910.8887,200,1,37,90
        ///4625.703,2958.8008,200,1,17,90
        ///7744,11776,200,1,28,86
        ///11532.419,8761.295,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_24 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6978,11360,200,1,13,153
        ///9406,5638,200,1,158,151
        ///3042,7342,200,1,11,136
        ///8286,3514,200,1,14,130
        ///9218,3876,200,1,33,129
        ///4798,7146,200,1,98,122
        ///5134,8556,200,1,39,115
        ///5470.3555,10458.418,200,1,66,109
        ///8570,6620,200,1,20,108
        ///9682,6392,200,1,51,103
        ///3128,8970,200,1,30,97
        ///6896,3064,200,1,29,95
        ///5472,3442,200,1,47,93
        ///8486,4894,200,1,76,91
        ///10626,3066,200,1,17,89
        ///4623.745,2857.7249,200,1,23,81
        ///8270,10204,200,1,134,79
        ///7910,11780,200,1,20,79
        ///6878.603,8619.5205,200,1,162,77
        ///9134,11408,200,1,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_27 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///2883.6245,8432.074,200,1,22,174
        ///3525.453,7414.722,200,1,11,155
        ///9422,5678,200,1,184,96
        ///5280,9186,200,1,101,96
        ///6606,4716,200,1,91,96
        ///9348,2186,200,1,19,93
        ///6920,5596,200,1,34,85
        ///10462,3100,200,1,105,78
        ///9710,6430,200,1,35,74
        ///4891.788,7164.8364,200,1,12,70
        ///11882.742,5962.2266,200,1,23,68
        ///3078,10844,200,1,242,67
        ///11098.841,2172.474,200,1,18,65
        ///11934,3700,200,1,175,63
        ///6344,8102,200,1,15,61
        ///8777.326,6718.3916,200,1,138,60
        ///5004,8428,200,1,29,54
        ///7919.361,9286.934,200,1,13,52
        ///12508,1432,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_3 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4924.2017,7107.814,200,1,21,156
        ///7010,3126,200,1,23,143
        ///9232.004,3874.455,200,1,18,136
        ///6520,4692,200,1,90,124
        ///8174,5758,200,1,14,123
        ///9440,5582,200,1,50,114
        ///3028,9042,200,1,20,110
        ///8578,4680,200,1,21,107
        ///9814.675,6517.2773,200,1,29,105
        ///4984,7978,200,1,12,102
        ///6348,10128,200,1,33,101
        ///7852,3560,200,1,14,99
        ///8316,10198,200,1,55,83
        ///6873.8916,8605.6875,200,1,110,77
        ///5428,3350,200,1,19,71
        ///11890.236,5972.0293,200,1,19,62
        ///10026,7842,200,1,18,49
        ///10673.852,9209.477,200,1,15,41
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_30 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6560,4728,200,1,51,138
        ///8542,4838,200,1,34,120
        ///4896.358,7160.4478,200,1,12,120
        ///6725.3184,3171.1074,200,1,11,120
        ///8258,10232,200,1,32,108
        ///9464,5616,200,1,43,105
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_33 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5290,9154,200,1,12,129
        ///6877.091,8607.867,200,1,19,94
        ///.
        /// </summary>
        public static string wards_Chaos_Regular_36 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10132,4686,200,1,13,120
        ///11122,2080,200,1,21,116
        ///3052,9052,200,1,24,112
        ///9140.588,4012.9128,200,1,16,94
        ///7838,3520,200,1,32,87
        ///6566,4770,200,1,61,85
        ///10648.577,3019.2402,200,1,744,80
        ///5156,9148,200,1,53,77
        ///9512,5584,200,1,80,75
        ///11828,3660,200,1,49,75
        ///8514,5710,200,1,32,73
        ///8544,4834,200,1,190,72
        ///6850,11412,200,1,12,72
        ///12888,1782,200,1,24,61
        ///12274,1262,200,1,69,60
        ///11998.037,5701.5107,200,1,25,59
        ///3066,10794,200,1,191,58
        ///8692,6668,200,1,54,58
        ///5416.84,12658.555,200,1,11,57
        ///4523.405,1266 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_6 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///7690,4984,200,1,11,88
        ///8460,5634,200,1,14,85
        ///12660,5260,200,1,13,81
        ///8608,4720,200,1,58,77
        ///3378,7738,200,1,12,77
        ///10629.365,3056.2407,200,1,871,74
        ///6620,4754,200,1,70,73
        ///11500,7098,200,1,17,72
        ///9364,5710,200,1,114,71
        ///6809.7266,5621.506,200,1,51,71
        ///9280,3770,200,1,18,70
        ///4600,11896,200,1,19,69
        ///11944.675,4114.4927,200,1,125,68
        ///9767.347,6465.9097,200,1,47,66
        ///5152,8542,200,1,35,64
        ///7096,3088,200,1,14,64
        ///5932.119,12807.785,200,1,37,63
        ///5720.8,7829.16,200,1,21,63
        ///6298,10130,200,1,15,61
        ///3084 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Chaos_Regular_9 {
            get {
                return ResourceManager.GetString("wards_Chaos_Regular_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6901.829,10586.238,100,3,29,275
        ///8296,10222,100,3,78,172
        ///7752,11758,100,3,22,170
        ///8576,4904,100,3,24,109
        ///7418,9722,100,3,14,109
        ///3372,7780,100,3,21,105
        ///9360,5622,100,3,107,90
        ///10254,2866,100,3,41,85
        ///11764,3948,100,3,22,83
        ///5234,9074,100,3,35,62
        ///9968,7876,100,3,11,54
        ///4368,11796,100,3,22,49
        ///12922,1966,100,3,26,37
        ///12214,1358,100,3,71,32
        ///13460,2580,100,3,40,23
        ///.
        /// </summary>
        public static string wards_Order_All_0 {
            get {
                return ResourceManager.GetString("wards_Order_All_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11574,7046,100,3,183,118
        ///11051.773,6156.707,100,3,20,116
        ///10924.436,8158.087,100,3,23,109
        ///8242,10178,100,3,180,105
        ///9418,5666,100,3,924,95
        ///9363.854,4660.377,100,3,39,94
        ///11752,5726,100,3,17,93
        ///7973.9453,9309.758,100,3,84,90
        ///10684,5008,100,3,20,88
        ///9766.976,6465.2583,100,3,149,87
        ///7070,3120,100,3,35,87
        ///5248,9104,100,3,363,86
        ///10092,3976,100,3,66,86
        ///11799.925,4897.7065,100,3,80,84
        ///3138,8984,100,3,25,83
        ///8566,4760,100,3,237,81
        ///3310,7800,100,3,98,80
        ///11409.591,3047.9644,100,3,61,79
        ///9088,2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_12 {
            get {
                return ResourceManager.GetString("wards_Order_All_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11596,7146,100,3,241,122
        ///9408.803,4705.3545,100,3,36,115
        ///9750,6404,100,3,600,109
        ///10658,4650,100,3,49,108
        ///11870,5870,100,3,195,103
        ///6472,10018,100,3,33,101
        ///11223.965,3207.8726,100,3,26,101
        ///9506,5626,100,3,487,100
        ///7840,3544,100,3,53,99
        ///8236,10244,100,3,396,97
        ///7018,11388,100,3,106,93
        ///3018.8271,8904.418,100,3,65,92
        ///6700,8984,100,3,51,92
        ///9110.014,7091.1523,100,3,194,89
        ///10034,7792,100,3,343,88
        ///7055.275,3151.6304,100,3,78,85
        ///5131.699,8443.176,100,3,146,84
        ///11772,4944,100,3,46,83
        ///8050,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_15 {
            get {
                return ResourceManager.GetString("wards_Order_All_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9366.625,4659.1777,100,3,81,129
        ///10178,4736,100,3,38,128
        ///11542,7204,100,3,142,127
        ///11904,5876,100,3,103,124
        ///9366,5668,100,3,673,108
        ///8284,10168,100,3,489,107
        ///7120.6406,8649.492,100,3,44,105
        ///7800,11834,100,3,94,103
        ///9756,3854,100,3,76,101
        ///9513.572,6934.308,100,3,123,98
        ///3416,7762,100,3,147,96
        ///7714,9406,100,3,21,95
        ///9352,11434,100,3,89,94
        ///9922.641,7807.2813,100,3,295,91
        ///7388.627,12670.273,100,3,27,88
        ///11768,8874,100,3,23,88
        ///8150,6222,100,3,1346,87
        ///4215.4604,9149.476,100,3,24,85
        ///8716,87 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_18 {
            get {
                return ResourceManager.GetString("wards_Order_All_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11367.84,9600.713,100,3,11,143
        ///11762,5986,100,3,79,139
        ///6748,9112,100,3,13,133
        ///5246,9172,100,3,634,123
        ///7840,11764,100,3,110,121
        ///4922,10166,100,3,108,121
        ///11724.811,5057.457,100,3,19,120
        ///8260,10200,100,3,1164,119
        ///6874,11444,100,3,44,119
        ///9354,4576,100,3,92,118
        ///9412,5660,100,3,669,114
        ///9914,3982,100,3,17,114
        ///8722,6690,100,3,16,108
        ///3436,7696,100,3,91,99
        ///9918.239,6605.4604,100,3,200,97
        ///9321.074,11508.309,100,3,91,96
        ///8017.522,6140.6416,100,3,114,94
        ///6874,3120,100,3,69,90
        ///6312,10078,100, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_21 {
            get {
                return ResourceManager.GetString("wards_Order_All_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10184,12076,100,3,13,152
        ///5128,9104,100,3,93,129
        ///11602,7152,100,3,112,125
        ///11686,5672,100,3,22,117
        ///8222,3578,100,3,26,114
        ///11800,8868,100,3,23,114
        ///8258,10172,100,3,370,111
        ///9658.161,3960.582,100,3,31,111
        ///11938,3808,100,3,17,110
        ///9160,11388,100,3,51,103
        ///6902,8884,100,3,26,103
        ///2965.871,8954.793,100,3,56,101
        ///4920,8312,100,3,56,101
        ///9506.8125,6944.115,100,3,55,101
        ///5650,12730,100,3,23,101
        ///9368,5686,100,3,338,100
        ///6308,10048,100,3,194,98
        ///7128,3076,100,3,37,94
        ///9416,4726,100,3,25,94
        ///8526,477 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_24 {
            get {
                return ResourceManager.GetString("wards_Order_All_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5288,9208,100,3,129,138
        ///9438,5650,100,3,283,122
        ///6426,10030,100,3,34,119
        ///8268,10234,100,3,295,118
        ///11762,5886,100,3,112,112
        ///4418,11802,100,3,37,106
        ///10066,7722,100,3,63,104
        ///7834,9314,100,3,33,103
        ///3328,7748,100,3,96,102
        ///7794,11786,100,3,48,102
        ///7052.4346,3150.979,100,3,46,102
        ///5046,8420,100,3,87,93
        ///9172.195,7055.379,100,3,38,92
        ///8032,3476,100,3,32,92
        ///9314,11412,100,3,66,89
        ///6518,4692,100,3,252,87
        ///8100,6200,100,3,176,85
        ///6560,8310,100,3,66,85
        ///10226,2880,100,3,35,85
        ///3074,10844,100,3,25,7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_27 {
            get {
                return ResourceManager.GetString("wards_Order_All_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11728,5880,100,3,71,123
        ///11576,7068,100,3,35,110
        ///7824.113,9290.322,100,3,36,95
        ///8290,10352,100,3,15,83
        ///9486,5600,100,3,168,82
        ///11710.092,5009.7197,100,3,19,80
        ///3330,7824,100,3,19,72
        ///1564,12874,100,3,14,72
        ///5338,9142,100,3,150,71
        ///12426,1422,100,3,86,67
        ///3074,10934,100,3,107,66
        ///10598,2998,100,3,85,65
        ///12890,3378,100,3,11,65
        ///5032.0283,8390.645,100,3,15,63
        ///13388,2560,100,3,276,62
        ///7022,11374,100,3,21,61
        ///11888,3744,100,3,249,60
        ///8082,6152,100,3,176,60
        ///12686,4980,100,3,11,57
        ///9886,6522,100,3, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_3 {
            get {
                return ResourceManager.GetString("wards_Order_All_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5171.0503,9994.798,100,3,26,177
        ///8242,10156,100,3,89,141
        ///7794,11786,100,3,13,131
        ///5340,9166,100,3,48,129
        ///9392,5612,100,3,136,119
        ///11802,5896,100,3,56,115
        ///12476,5198,100,3,12,109
        ///9322,4530,100,3,33,107
        ///3404,7740,100,3,26,103
        ///4121.8906,9205.352,100,3,24,97
        ///10002,6622,100,3,36,95
        ///9390,11432,100,3,39,86
        ///7892,3524,100,3,27,86
        ///5538.465,3411.4424,100,3,22,85
        ///8526,4712,100,3,46,83
        ///6973.5723,3107.0303,100,3,23,83
        ///5766,10668,100,3,18,83
        ///6566,4746,100,3,118,80
        ///8096,6202,100,3,107,79
        ///11221.4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_30 {
            get {
                return ResourceManager.GetString("wards_Order_All_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8308,10220,100,3,43,129
        ///10008,6594,100,3,23,129
        ///11067.224,6154.742,100,3,11,129
        ///5688,3540,100,3,17,123
        ///5224,9182,100,3,55,114
        ///6172.91,8095.4287,100,3,11,107
        ///6276,10184,100,3,47,99
        ///8484,4822,100,3,28,97
        ///9460,5682,100,3,57,95
        ///6564,4600,100,3,27,81
        ///11532,7186,100,3,19,79
        ///9314,11460,100,3,20,77
        ///10344,3106,100,3,12,73
        ///10074,7774,100,3,26,71
        ///8108,6202,100,3,45,70
        ///3408,7818,100,3,11,70
        ///.
        /// </summary>
        public static string wards_Order_All_33 {
            get {
                return ResourceManager.GetString("wards_Order_All_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5232,9178,100,3,19,135
        ///6524,4660,100,3,13,87
        ///.
        /// </summary>
        public static string wards_Order_All_36 {
            get {
                return ResourceManager.GetString("wards_Order_All_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10238,4766,100,3,14,155
        ///11586,7076,100,3,76,140
        ///11812,5908,100,3,186,124
        ///9409.708,4703.956,100,3,17,112
        ///7020,11352,100,3,46,111
        ///9420,5592,100,3,397,100
        ///9474,2176,100,3,11,99
        ///5284,9148,100,3,205,96
        ///9780,3938,100,3,26,94
        ///8524,4890,100,3,95,88
        ///11669.566,5104.5625,100,3,34,87
        ///9654.372,6429.807,100,3,30,86
        ///11750,4064,100,3,551,84
        ///6610,9084,100,3,17,81
        ///8366,6348,100,3,92,80
        ///6318,10070,100,3,83,77
        ///7876.8496,9283.973,100,3,40,77
        ///11208.271,3185.483,100,3,33,76
        ///10300,2940,100,3,685,72
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_6 {
            get {
                return ResourceManager.GetString("wards_Order_All_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11922.343,6496.375,100,3,34,119
        ///11896,5676,100,3,20,119
        ///11398,7218,100,3,11,117
        ///8266,10322,100,3,27,109
        ///3398,7726,100,3,35,99
        ///9376,5660,100,3,675,98
        ///2994,9108,100,3,21,96
        ///7736,11786,100,3,21,95
        ///10178.921,3994.8657,100,3,79,91
        ///12674.191,4897.9463,100,3,213,82
        ///8498,4910,100,3,102,79
        ///7975.2437,9296.416,100,3,37,75
        ///11299.496,3135.955,100,3,21,74
        ///6336,10042,100,3,97,71
        ///9920,6530,100,3,89,71
        ///5152,8560,100,3,68,71
        ///10350,3152,100,3,135,69
        ///5426.465,12657.316,100,3,34,65
        ///11918,3812,100, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_All_9 {
            get {
                return ResourceManager.GetString("wards_Order_All_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8196,10184,100,2,11,112
        ///9420,5678,100,2,16,74
        ///6298,10084,100,2,11,72
        ///.
        /// </summary>
        public static string wards_Order_Blue_12 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9950,7778,100,2,23,95
        ///11772,5880,100,2,14,80
        ///9434,5644,100,2,45,76
        ///3324,7826,100,2,12,69
        ///6304,10096,100,2,24,65
        ///8586,4786,100,2,22,63
        ///10438,3080,100,2,13,62
        ///6978,11416,100,2,13,58
        ///8338,6446,100,2,22,57
        ///5230,9126,100,2,14,57
        ///4796,7174,100,2,17,54
        ///9898,6548,100,2,20,49
        ///6604,4682,100,2,19,41
        ///6338,8188,100,2,13,37
        ///.
        /// </summary>
        public static string wards_Order_Blue_15 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11878,5848,100,2,20,115
        ///5132,8558,100,2,15,104
        ///11474,7124,100,2,30,95
        ///9466,5720,100,2,28,89
        ///6316,10114,100,2,30,84
        ///8294,10312,100,2,90,80
        ///7024,11302,100,2,15,71
        ///3402,7734,100,2,29,58
        ///9970,6560,100,2,28,58
        ///9940,7808,100,2,36,57
        ///8038,3512,100,2,18,57
        ///6656,4680,100,2,27,56
        ///8514,4826,100,2,27,56
        ///8340,6420,100,2,29,53
        ///12472,5156,100,2,11,46
        ///.
        /// </summary>
        public static string wards_Order_Blue_18 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11532,7078,100,2,24,107
        ///9480,5652,100,2,47,102
        ///8154,10112,100,2,12,88
        ///7908,3490,100,2,12,88
        ///6628,8336,100,2,14,87
        ///11856,5896,100,2,38,81
        ///9904,6556,100,2,39,79
        ///8072,11826,100,2,23,74
        ///6278.846,10208.662,100,2,52,73
        ///10456,3084,100,2,28,67
        ///7018,3110,100,2,18,65
        ///4434,11858,100,2,16,62
        ///12530,5064,100,2,16,57
        ///4823.286,7207.837,100,2,20,54
        ///11850,3926,100,2,14,52
        ///8326,6424,100,2,28,47
        ///9212,2088,100,2,22,45
        ///.
        /// </summary>
        public static string wards_Order_Blue_21 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9434,5580,100,2,24,94
        ///4840,10222,100,2,21,78
        ///9860,6464,100,2,32,72
        ///12542,5092,100,2,16,71
        ///10052,7824,100,2,32,70
        ///5086,8554,100,2,12,70
        ///8282,10210,100,2,58,68
        ///7916,11826,100,2,16,64
        ///6608,4698,100,2,59,63
        ///9278,2098,100,2,15,63
        ///4868,7156,100,2,18,62
        ///11858,4012,100,2,19,58
        ///5642,3564,100,2,15,43
        ///.
        /// </summary>
        public static string wards_Order_Blue_24 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11582,7098,100,2,19,135
        ///9412,5664,100,2,26,117
        ///6240,10404,100,2,14,84
        ///9756,6442,100,2,21,83
        ///8218,10342,100,2,14,83
        ///6528,4700,100,2,34,81
        ///5680,3520,100,2,19,70
        ///9990,7938,100,2,25,66
        ///10350,3100,100,2,18,51
        ///12500,5112,100,2,12,51
        ///7046,3086,100,2,14,49
        ///11792,3976,100,2,13,36
        ///.
        /// </summary>
        public static string wards_Order_Blue_27 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8282,10230,100,2,26,116
        ///10060,7898,100,2,11,103
        ///6316,10168,100,2,13,85
        ///4784,10272,100,2,11,80
        ///9173.908,11415.844,100,2,11,72
        ///9370,5642,100,2,15,70
        ///8556,4712,100,2,12,37
        ///.
        /// </summary>
        public static string wards_Order_Blue_30 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9474,5646,100,2,13,79
        ///6618,4742,100,2,11,52
        ///.
        /// </summary>
        public static string wards_Order_Blue_33 {
            get {
                return ResourceManager.GetString("wards_Order_Blue_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11708,5874,100,0,121,138
        ///11630,7086,100,0,87,129
        ///8288,10270,100,0,52,103
        ///9496,5576,100,0,153,100
        ///10052,7798,100,0,81,92
        ///7768,11824,100,0,34,92
        ///3274,7790,100,0,49,91
        ///5282,9090,100,0,156,90
        ///3020,9016,100,0,39,90
        ///11760,4026,100,0,310,86
        ///5464,12686,100,0,13,84
        ///8100,3472,100,0,38,82
        ///12362,1396,100,0,21,82
        ///8628,4804,100,0,50,78
        ///10260,2888,100,0,1464,77
        ///3096,10872,100,0,216,77
        ///8220,6272,100,0,208,76
        ///4240,11816,100,0,38,76
        ///9766.35,3844.0544,100,0,13,75
        ///6312,10150,100,0,64,71
        ///9070,2062 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_12 {
            get {
                return ResourceManager.GetString("wards_Order_Control_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9762.745,6453.3525,100,0,53,116
        ///11888,5842,100,0,58,109
        ///8258,10106,100,0,32,108
        ///6978,11404,100,0,24,108
        ///9418,5710,100,0,374,106
        ///5188,9134,100,0,243,106
        ///11436,7180,100,0,24,102
        ///3398,7752,100,0,50,97
        ///10128,4726,100,0,59,94
        ///4438,11746,100,0,47,91
        ///7794,11792,100,0,43,91
        ///8090,3436,100,0,16,91
        ///9972,7830,100,0,92,90
        ///4818,10114,100,0,20,90
        ///10322,2930,100,0,396,85
        ///8480,4788,100,0,188,83
        ///6286,10088,100,0,100,83
        ///3014,9056,100,0,31,81
        ///7006,3026,100,0,13,79
        ///11758,4050,100,0,144,78
        ///12254,12 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_15 {
            get {
                return ResourceManager.GetString("wards_Order_Control_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9168,11424,100,0,11,137
        ///11634,7102,100,0,89,130
        ///6764,3110,100,0,14,122
        ///9738,6384,100,0,66,121
        ///7930,11878,100,0,26,112
        ///3390,7730,100,0,64,108
        ///9402,5616,100,0,340,107
        ///11804,5878,100,0,109,106
        ///5286,9122,100,0,213,104
        ///9368,4540,100,0,29,103
        ///8268,10172,100,0,123,99
        ///10050,7762,100,0,146,96
        ///7966,3416,100,0,14,95
        ///2966.9866,8951.195,100,0,36,89
        ///12582,5272,100,0,21,87
        ///4288,11838,100,0,26,85
        ///6520,8392,100,0,19,85
        ///2954,11158,100,0,21,83
        ///8102,6200,100,0,164,81
        ///8584,4774,100,0,144,81
        ///6280,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_18 {
            get {
                return ResourceManager.GetString("wards_Order_Control_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9942,6562,100,0,33,142
        ///5196,8506,100,0,37,133
        ///6218,10256,100,0,33,129
        ///8234,10234,100,0,110,126
        ///8080,3474,100,0,11,119
        ///10106,8016,100,0,12,114
        ///11862,5840,100,0,46,112
        ///9116,2108,100,0,14,107
        ///11590,7080,100,0,65,105
        ///9374,5650,100,0,212,101
        ///3022,8960,100,0,40,101
        ///3294,7728,100,0,53,99
        ///8336,6428,100,0,42,95
        ///8524,4822,100,0,131,91
        ///9356,11442,100,0,21,91
        ///7923.3057,11758.832,100,0,25,90
        ///11740,4014,100,0,36,82
        ///6316,8146,100,0,88,80
        ///6526,4600,100,0,63,80
        ///10326,3090,100,0,32,79
        ///3050,1075 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_21 {
            get {
                return ResourceManager.GetString("wards_Order_Control_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6944,11396,100,0,13,150
        ///11550,7134,100,0,47,127
        ///6860,3050,100,0,12,119
        ///3430,7712,100,0,21,112
        ///9490,5580,100,0,44,110
        ///4874,10170,100,0,92,101
        ///8250,10194,100,0,74,98
        ///5344,9162,100,0,31,95
        ///4234,11810,100,0,12,95
        ///8550,4712,100,0,54,92
        ///4752,7190,100,0,45,90
        ///3062,9006,100,0,32,85
        ///6562,4680,100,0,140,84
        ///8256,6342,100,0,36,83
        ///9118,11390,100,0,11,82
        ///9930,6538,100,0,21,81
        ///8066,3462,100,0,12,79
        ///6228,10206,100,0,34,78
        ///7808,11842,100,0,12,77
        ///10328,2972,100,0,32,76
        ///5573.148,3505.3586,100,0, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_24 {
            get {
                return ResourceManager.GetString("wards_Order_Control_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///3132,8984,100,0,11,129
        ///9404,5642,100,0,106,124
        ///8273.627,10111.393,100,0,16,105
        ///3398,7830,100,0,11,104
        ///4995.032,8342.28,100,0,16,102
        ///10358,3018,100,0,13,97
        ///11750,5906,100,0,21,87
        ///6267.4087,8057.077,100,0,16,87
        ///5654,3542,100,0,19,85
        ///11744,4012,100,0,13,85
        ///7034,3098,100,0,13,83
        ///6576,4692,100,0,87,81
        ///9762.782,6451.376,100,0,15,81
        ///8216,6248,100,0,31,80
        ///9974,7794,100,0,34,77
        ///8526,4806,100,0,56,74
        ///9410,4202,100,0,16,59
        ///4770,7070,100,0,14,56
        ///.
        /// </summary>
        public static string wards_Order_Control_27 {
            get {
                return ResourceManager.GetString("wards_Order_Control_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11716,5844,100,0,12,121
        ///11606,7080,100,0,15,96
        ///9392,5628,100,0,86,87
        ///10354,3124,100,0,36,84
        ///11800,4048,100,0,48,81
        ///5294,9160,100,0,30,69
        ///8496,4828,100,0,21,69
        ///8270,6320,100,0,35,57
        ///.
        /// </summary>
        public static string wards_Order_Control_3 {
            get {
                return ResourceManager.GetString("wards_Order_Control_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11746,5930,100,0,14,215
        ///5118,8472,100,0,23,146
        ///4892,10072,100,0,11,137
        ///9984,7840,100,0,13,131
        ///8282,10284,100,0,13,125
        ///9430,5704,100,0,34,114
        ///11550,7108,100,0,12,113
        ///6248,10108,100,0,14,105
        ///8502,4832,100,0,26,89
        ///6522,4704,100,0,40,84
        ///6324,8104,100,0,20,82
        ///3272,7786,100,0,12,81
        ///3040,8966,100,0,14,73
        ///.
        /// </summary>
        public static string wards_Order_Control_30 {
            get {
                return ResourceManager.GetString("wards_Order_Control_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4834,10174,100,0,14,221
        ///5208,9166,100,0,16,130
        ///9450,5642,100,0,22,96
        ///6582,4690,100,0,12,75
        ///.
        /// </summary>
        public static string wards_Order_Control_33 {
            get {
                return ResourceManager.GetString("wards_Order_Control_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///11594,7042,100,0,43,154
        ///11746,5932,100,0,92,139
        ///6286,10196,100,0,20,121
        ///8300,10262,100,0,26,114
        ///10030,7810,100,0,17,113
        ///8526,4776,100,0,82,112
        ///5376,9140,100,0,41,111
        ///7046,11352,100,0,16,110
        ///9460,5576,100,0,145,108
        ///10072,4674,100,0,55,103
        ///9710,6354,100,0,40,89
        ///4190,11852,100,0,16,85
        ///8124,6216,100,0,206,84
        ///3060,8918,100,0,12,83
        ///11864,4028,100,0,127,79
        ///10248,2942,100,0,579,74
        ///2890,11100,100,0,34,73
        ///7784,11796,100,0,21,68
        ///6392,8240,100,0,46,54
        ///12908,1924,100,0,17,54
        ///12160,1280,100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_6 {
            get {
                return ResourceManager.GetString("wards_Order_Control_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8268,10270,100,0,26,148
        ///11546,7048,100,0,42,137
        ///11756,5892,100,0,137,131
        ///9370,5690,100,0,379,100
        ///7736,11786,100,0,15,99
        ///9932,6602,100,0,19,97
        ///5218,9180,100,0,229,89
        ///3108,8984,100,0,18,85
        ///11852,3702,100,0,84,82
        ///10190,4544,100,0,26,81
        ///6306,10134,100,0,80,79
        ///8500,4828,100,0,304,77
        ///12356,1304,100,0,12,77
        ///3086,10854,100,0,255,74
        ///10038,7780,100,0,53,74
        ///8200,6294,100,0,220,73
        ///10272,2944,100,0,896,71
        ///12982,1956,100,0,25,70
        ///4460,11868,100,0,19,66
        ///6608,4798,100,0,11,66
        ///9500.334,4090.138 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Control_9 {
            get {
                return ResourceManager.GetString("wards_Order_Control_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6906.5996,10596.539,100,1,29,275
        ///10720.457,6897.4355,100,1,18,244
        ///10354,2972,100,1,49,160
        ///8218,10308,100,1,45,151
        ///9410,5704,100,1,93,106
        ///3419.0706,7692.563,100,1,16,106
        ///8200,3500,100,1,14,93
        ///7824.8633,9297.215,100,1,24,91
        ///8567.605,4607.8994,100,1,18,90
        ///11704,4056,100,1,15,85
        ///5318,9072,100,1,22,66
        ///12330,5218,100,1,12,59
        ///13420,2680,100,1,19,30
        ///2934,11310,100,1,17,28
        ///12430,1348,100,1,17,20
        ///.
        /// </summary>
        public static string wards_Order_Regular_0 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10496,4342,100,1,21,123
        ///11734,5902,100,1,268,103
        ///2918,9146,100,1,12,97
        ///9444,5702,100,1,307,96
        ///7078,3122,100,1,20,95
        ///8292,10234,100,1,115,93
        ///11723.271,5007.592,100,1,99,92
        ///9421.858,4147.5,100,1,35,92
        ///11217.75,3195.8633,100,1,30,91
        ///9784,6440,100,1,116,90
        ///9909.172,7805.1035,100,1,70,84
        ///8060,7788,100,1,16,82
        ///5186,9126,100,1,111,81
        ///8219.735,3556.5586,100,1,13,80
        ///12692,4948,100,1,225,79
        ///6316,10044,100,1,49,78
        ///6672.8184,9007.121,100,1,29,78
        ///8518.7,4706.2607,100,1,44,73
        ///11908,3788,100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_12 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6572,9988,100,1,12,143
        ///11604,7086,100,1,128,118
        ///11800,5936,100,1,188,112
        ///8258,10202,100,1,317,101
        ///7796,11784,100,1,78,101
        ///11371.003,3104.4138,100,1,23,97
        ///4854,7124,100,1,39,90
        ///2904.5664,8999.783,100,1,34,87
        ///9992,6528,100,1,159,86
        ///5070,8512,100,1,91,86
        ///8414,6432,100,1,83,85
        ///10450,3078,100,1,143,84
        ///8582,4804,100,1,126,84
        ///5884,12752,100,1,54,83
        ///6518,4714,100,1,200,82
        ///7840,7856,100,1,34,82
        ///9567.971,4059.896,100,1,56,80
        ///6680,11524,100,1,11,78
        ///9916.215,7807.9277,100,1,153,77
        ///9318.22 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_15 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///10640,4638,100,1,33,142
        ///4748,10174,100,1,13,141
        ///8870,8786,100,1,14,126
        ///11816,5876,100,1,125,120
        ///8288,10212,100,1,378,116
        ///9370,5676,100,1,373,114
        ///11003.679,6509.6064,100,1,15,112
        ///10124.36,3956.96,100,1,33,110
        ///10004,6606,100,1,166,103
        ///7818,11838,100,1,48,97
        ///7714,9406,100,1,19,97
        ///3494,7756,100,1,33,93
        ///9073.49,11409.074,100,1,22,93
        ///8582,4716,100,1,102,91
        ///8134,6174,100,1,455,89
        ///9169.527,7051.035,100,1,175,88
        ///8074.036,3505.6436,100,1,50,85
        ///5274,9196,100,1,193,84
        ///6284,10154,100,1,210 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_18 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4674,10002,100,1,18,309
        ///10634,4600,100,1,13,147
        ///8312,10422,100,1,14,131
        ///7900,11776,100,1,63,126
        ///7671.0723,9294.381,100,1,42,125
        ///11660.463,5105.1855,100,1,25,122
        ///9666.445,6888.879,100,1,75,120
        ///11768,5912,100,1,101,119
        ///11618,7060,100,1,38,119
        ///9192,11404,100,1,27,115
        ///9374,5712,100,1,209,113
        ///7042,3058,100,1,37,111
        ///5817.4146,10309.017,100,1,30,110
        ///6964,11400,100,1,64,102
        ///9370.041,4658.133,100,1,52,101
        ///8052,7952,100,1,22,98
        ///10022,7760,100,1,120,92
        ///3274.482,7711.0625,100,1,58,92
        ///7009 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_21 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///9110,11368,100,1,22,139
        ///5124.7,9993.796,100,1,31,137
        ///12020,7464,100,1,32,130
        ///11728,5944,100,1,59,129
        ///5008,8498,100,1,39,121
        ///5715.7266,10860.6,100,1,24,120
        ///12178,10306,100,1,31,117
        ///10074.209,3907.0933,100,1,12,116
        ///8332,10240,100,1,178,114
        ///8268,3482,100,1,14,112
        ///9353.335,4563.6255,100,1,58,106
        ///7824.6904,9313.115,100,1,41,100
        ///9904,6558,100,1,111,99
        ///6540,4586,100,1,95,99
        ///9324,5672,100,1,101,98
        ///2266,9560,100,1,11,98
        ///6272,10130,100,1,193,96
        ///6661.491,3794.7256,100,1,18,96
        ///4838,7088,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_24 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///5146,10008,100,1,25,313
        ///11600,7148,100,1,35,151
        ///10909.583,8137.223,100,1,11,138
        ///7074,3094,100,1,36,135
        ///9474,5638,100,1,109,132
        ///8294,10202,100,1,181,117
        ///5045.795,8385.975,100,1,67,108
        ///9905.934,7801.1523,100,1,58,100
        ///6594,4726,100,1,138,98
        ///9169.25,7033.4785,100,1,33,98
        ///8188,11704,100,1,30,96
        ///9824,6454,100,1,68,89
        ///8122,6224,100,1,144,87
        ///7824.2744,9302.883,100,1,29,85
        ///10350,3196,100,1,11,85
        ///9706,3910,100,1,28,80
        ///12108,10236,100,1,12,78
        ///3058,8976,100,1,15,77
        ///9370,11464,100,1,52,75
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_27 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///2910.4253,9010.799,100,1,14,110
        ///11208.123,3191.5537,100,1,40,83
        ///8194,10108,100,1,32,83
        ///7724.3887,9302.625,100,1,22,83
        ///9410,5744,100,1,88,80
        ///12638,4954,100,1,31,77
        ///6968,11344,100,1,15,69
        ///5136,8550,100,1,12,69
        ///3034,10790,100,1,40,68
        ///12920.289,3458.586,100,1,11,68
        ///11774,4004,100,1,531,67
        ///9818,6500,100,1,27,67
        ///13010,1876,100,1,86,61
        ///4494,11948,100,1,13,61
        ///13454,2544,100,1,222,59
        ///6714,9152,100,1,11,58
        ///10211.809,2195.9316,100,1,12,56
        ///6510,8252,100,1,89,50
        ///12240,1360,100,1,324,45
        ///782 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_3 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8218,10102,100,1,22,158
        ///5176,9162,100,1,94,154
        ///9300.164,4499.636,100,1,21,129
        ///10044,7790,100,1,39,128
        ///9982,6578,100,1,44,120
        ///11570,7118,100,1,23,108
        ///3300,7738,100,1,18,105
        ///9362,5716,100,1,39,103
        ///11069.121,6153.965,100,1,12,103
        ///4123.705,9206.568,100,1,23,101
        ///7777.5703,9286.758,100,1,21,101
        ///8170,11718,100,1,13,100
        ///5762.2666,10706.178,100,1,20,94
        ///7059.3223,8705.181,100,1,14,89
        ///5675.742,3503.024,100,1,21,87
        ///8130,6222,100,1,89,76
        ///6234,8100,100,1,58,72
        ///4832,7106,100,1,24,70
        ///6480,469 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_30 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///8264,10232,100,1,35,167
        ///5146,9102,100,1,12,146
        ///9952,7776,100,1,15,100
        ///6550,4714,100,1,38,99
        ///9442,5642,100,1,30,99
        ///8082,6204,100,1,38,75
        ///9336,11478,100,1,18,68
        ///.
        /// </summary>
        public static string wards_Order_Regular_33 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6530,4678,100,1,11,95
        ///.
        /// </summary>
        public static string wards_Order_Regular_36 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///6996,11366,100,1,30,102
        ///9442,2146,100,1,11,96
        ///9430,5614,100,1,196,90
        ///11906,3870,100,1,139,84
        ///9930,6542,100,1,52,81
        ///8336,10266,100,1,22,79
        ///7923.8457,9308.33,100,1,34,73
        ///11886,4828,100,1,30,71
        ///7996,7820,100,1,34,69
        ///9702.732,3918.4685,100,1,19,69
        ///5322,9108,100,1,38,67
        ///7852,3590,100,1,13,66
        ///13444,2478,100,1,171,61
        ///11309.215,3146.7666,100,1,15,61
        ///6324,10114,100,1,29,59
        ///4242,11844,100,1,164,55
        ///10290,2908,100,1,114,54
        ///8636,4536,100,1,12,54
        ///12868,1856,100,1,187,53
        ///2902,11260,100,1,265 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_6 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,team,type,popularity,score
        ///4467.9824,10458.455,100,1,11,118
        ///11411.066,3040.314,100,1,35,94
        ///11840,5894,100,1,114,93
        ///9866.542,7954.0884,100,1,13,92
        ///5186,9166,100,1,111,85
        ///8208,10162,100,1,22,81
        ///2966.7817,8956.271,100,1,18,81
        ///12627.633,4853.949,100,1,192,80
        ///9374,5718,100,1,170,80
        ///5472,12722,100,1,17,73
        ///9772,6912,100,1,20,72
        ///11848,3938,100,1,433,68
        ///10604,3096,100,1,42,66
        ///6304,9276,100,1,11,59
        ///7034,11348,100,1,23,58
        ///4478,11784,100,1,83,57
        ///6266,10112,100,1,56,57
        ///6873.8076,5612.1836,100,1,31,57
        ///13356,2524,100, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wards_Order_Regular_9 {
            get {
                return ResourceManager.GetString("wards_Order_Regular_9", resourceCulture);
            }
        }
    }
}
